"""Minor Arcana - Suit of Swords (14 cards) for the Rider-Waite-Smith Tarot Canon."""

from typing import List
from .models import ArcanaType, CardMeaning, Element, Suit, TarotCard

SWORDS: List[TarotCard] = [
    TarotCard(
        id="ace_of_swords",
        name="Ace of Swords",
        name_zh="宝剑一",
        arcana=ArcanaType.MINOR,
        number=1,
        suit=Suit.SWORDS,
        element=Element.AIR,
        astrology="Root of the Powers of Air",
        archetype="The Sword of Truth / Intellectual Breakthrough",
        keywords=CardMeaning(
            upright=["Clarity", "Breakthrough", "Sharp Mind", "Truth", "New Ideas", "Mental Power"],
            reversed=["Confusion", "Hostility", "Misinformation", "Brutality", "Clouded Judgement"],
        ),
        description="A divine hand emerges from a cloud gripping a double-edged sword upright, crowned with a golden coronet adorned with olive and palm branches against a mountainous backdrop.",
        upright_interpretation="A piercing breakthrough of mental clarity, objective truth, sharp analytical insight, and decisive intellect.",
        reversed_interpretation="Mental fog, harsh cruelty, deceptive communication, or misusing intellect to cause unnecessary harm.",
    ),
    TarotCard(
        id="two_of_swords",
        name="Two of Swords",
        name_zh="宝剑二",
        arcana=ArcanaType.MINOR,
        number=2,
        suit=Suit.SWORDS,
        element=Element.AIR,
        astrology="Moon in Libra",
        archetype="The Stalemate / Blindfold of Neutrality",
        keywords=CardMeaning(
            upright=["Stalemate", "Difficult Choice", "Truce", "Blocked Emotions", "Indecision", "Balance"],
            reversed=["Indecision Resolved", "Information Overload", "Lies Exposed", "Emotional Release"],
        ),
        description="A blindfolded woman in white sits on a stone bench beside a calm sea with jagged rocks, holding two crossed swords across her chest under a crescent moon.",
        upright_interpretation="A delicate truce or difficult dilemma requiring balanced impartiality before making a critical choice.",
        reversed_interpretation="Forced to make a postponed decision as new information breaks the stalemate; emotional floodgates opening.",
    ),
    TarotCard(
        id="three_of_swords",
        name="Three of Swords",
        name_zh="宝剑三",
        arcana=ArcanaType.MINOR,
        number=3,
        suit=Suit.SWORDS,
        element=Element.AIR,
        astrology="Saturn in Libra",
        archetype="The Pierced Heart / Sorrow",
        keywords=CardMeaning(
            upright=["Heartbreak", "Emotional Pain", "Grief", "Betrayal", "Separation", "Sorrow"],
            reversed=["Healing", "Forgiveness", "Releasing Pain", "Overcoming Grief", "Recovery"],
        ),
        description="A large red heart is pierced through by three swords, floating against dark storm clouds and torrential rain.",
        upright_interpretation="Acute emotional sorrow, painful rejection, honest realization of a painful truth, or heartbreak.",
        reversed_interpretation="The storm begins to clear, allowing gentle healing, release of lingering resentment, and emotional recovery.",
    ),
    TarotCard(
        id="four_of_swords",
        name="Four of Swords",
        name_zh="宝剑四",
        arcana=ArcanaType.MINOR,
        number=4,
        suit=Suit.SWORDS,
        element=Element.AIR,
        astrology="Jupiter in Libra",
        archetype="The Sacred Sanctuary / Rest & Recuperation",
        keywords=CardMeaning(
            upright=["Rest", "Restoration", "Contemplation", "Recovery", "Recuperation", "Peace"],
            reversed=["Exhaustion", "Burnout", "Forced Rest", "Restlessness", "Returning to Action"],
        ),
        description="An effigy of a knight lies in quiet repose atop a tomb with hands in prayer, below three hanging swords while a fourth sword lies beside his side below a stained-glass window.",
        upright_interpretation="Step back from the battlefield of daily life to rest your mind, recuperate your strength, and find sanctuary.",
        reversed_interpretation="Ignoring signs of severe exhaustion, or conversely, emerging refreshed and ready to re-enter active life.",
    ),
    TarotCard(
        id="five_of_swords",
        name="Five of Swords",
        name_zh="宝剑五",
        arcana=ArcanaType.MINOR,
        number=5,
        suit=Suit.SWORDS,
        element=Element.AIR,
        astrology="Venus in Aquarius",
        archetype="The Pyrrhic Victory / Hollow Triumph",
        keywords=CardMeaning(
            upright=["Defeat", "Conflict", "Hollow Victory", "Betrayal", "Hostility", "Self-interest"],
            reversed=["Reconciliation", "Compromise", "Forgiveness", "Moving Past Resentment", "Regret"],
        ),
        description="A smirking man holds three swords and looks over his shoulder at two defeated companions walking away in sorrow beneath jagged storm clouds.",
        upright_interpretation="A win that costs too much; discord and ruthlessness leaving behind bitterness. Choose your battles carefully.",
        reversed_interpretation="Desire to lay down arms, seek sincere reconciliation, and put an end to mutually destructive disputes.",
    ),
    TarotCard(
        id="six_of_swords",
        name="Six of Swords",
        name_zh="宝剑六",
        arcana=ArcanaType.MINOR,
        number=6,
        suit=Suit.SWORDS,
        element=Element.AIR,
        astrology="Mercury in Aquarius",
        archetype="The Rite of Passage / Ferry to Calmer Waters",
        keywords=CardMeaning(
            upright=["Transition", "Calmer Waters", "Moving On", "Travel", "Healing Journey", "Relief"],
            reversed=["Emotional Baggage", "Rough Waters", "Resistance to Transition", "Trapped"],
        ),
        description="A ferryman poles a wooden boat carrying a cloaked woman and child across water toward a peaceful shore, with six upright swords standing inside the boat.",
        upright_interpretation="Gradual transition from turbulent distress toward calmer emotional shores and mental recovery.",
        reversed_interpretation="Carrying unresolved psychological baggage into new beginnings, or struggling against an unavoidable life transition.",
    ),
    TarotCard(
        id="seven_of_swords",
        name="Seven of Swords",
        name_zh="宝剑七",
        arcana=ArcanaType.MINOR,
        number=7,
        suit=Suit.SWORDS,
        element=Element.AIR,
        astrology="Moon in Aquarius",
        archetype="The Cunning Infiltrator / Stealth",
        keywords=CardMeaning(
            upright=["Strategy", "Stealth", "Cunning", "Deception", "Sneakiness", "Resourcefulness"],
            reversed=["Confession", "Caught Out", "Coming Clean", "Imposter Syndrome", "Transparency"],
        ),
        description="A cunning figure tiptoes away from a military encampment carrying five swords in his arms while glancing back at two remaining swords stuck in the ground.",
        upright_interpretation="Tactical strategy, acting with discretion, or solving problems through clever finesse rather than head-on combat.",
        reversed_interpretation="Deceptions coming to light, confessing wrongdoing, or suffering from fear of being exposed.",
    ),
    TarotCard(
        id="eight_of_swords",
        name="Eight of Swords",
        name_zh="宝剑八",
        arcana=ArcanaType.MINOR,
        number=8,
        suit=Suit.SWORDS,
        element=Element.AIR,
        astrology="Jupiter in Gemini",
        archetype="The Self-Imposed Prison / Helplessness",
        keywords=CardMeaning(
            upright=["Imprisonment", "Self-victimization", "Limiting Beliefs", "Feeling Trapped", "Helplessness", "Blindness"],
            reversed=["Freedom", "Self-empowerment", "New Perspective", "Release", "Escaping Restrictions"],
        ),
        description="A bound and blindfolded woman stands in mud surrounded by an enclosure of eight swords, though her legs are free and paths out exist.",
        upright_interpretation="Feeling paralyzed by limiting mental scripts and perceived traps that are largely psychological.",
        reversed_interpretation="Shedding the blindfold of victimhood, recognizing freedom, and taking decisive steps toward self-liberation.",
    ),
    TarotCard(
        id="nine_of_swords",
        name="Nine of Swords",
        name_zh="宝剑九",
        arcana=ArcanaType.MINOR,
        number=9,
        suit=Suit.SWORDS,
        element=Element.AIR,
        astrology="Mars in Gemini",
        archetype="The Nightmare / 3 AM Anxiety",
        keywords=CardMeaning(
            upright=["Anxiety", "Nightmares", "Worry", "Guilt", "Insomnia", "Overthinking"],
            reversed=["Hope", "Reaching Out", "Overcoming Anxiety", "Facing Fears", "Light at the End of the Tunnel"],
        ),
        description="A person sits up in bed in the dark with face buried in hands in anguish, beneath nine swords hanging horizontally against a black wall.",
        upright_interpretation="Sleepless anxiety, excessive worry, and catastrophic mental loops magnifying problems beyond reality.",
        reversed_interpretation="Emerging from dark mental tunnels, seeking supportive counsel, and realizing fears were worse in the imagination than reality.",
    ),
    TarotCard(
        id="ten_of_swords",
        name="Ten of Swords",
        name_zh="宝剑十",
        arcana=ArcanaType.MINOR,
        number=10,
        suit=Suit.SWORDS,
        element=Element.AIR,
        astrology="Sun in Gemini",
        archetype="The Ultimate Ending / Dawn after the Dark",
        keywords=CardMeaning(
            upright=["Painful Ending", "Rock Bottom", "Betrayal", "Defeat", "Inevitable Conclusion", "Dawn"],
            reversed=["Recovery", "Regeneration", "Resurrection", "Near-death Escape", "Relief"],
        ),
        description="A figure lies face down pinned by ten swords in the back beside a calm black sea, while the golden dawn breaks on the distant horizon.",
        upright_interpretation="Rock bottom has been reached; the painful cycle is decisively over and the dawn of a new day begins.",
        reversed_interpretation="Rising from defeat, slowly rebuilding after severe collapse, and reclaiming vital life energy.",
    ),
    TarotCard(
        id="page_of_swords",
        name="Page of Swords",
        name_zh="宝剑侍从",
        arcana=ArcanaType.MINOR,
        number=11,
        suit=Suit.SWORDS,
        element=Element.AIR,
        astrology="Earth of Air",
        archetype="The Inquisitive Scout / Alert Student",
        keywords=CardMeaning(
            upright=["Curiosity", "Vigilance", "Mental Agility", "Direct Communication", "New Ideas", "Scouting"],
            reversed=["Gossip", "Deceit", "Paranoia", "All Talk No Action", "Sharp Tongue"],
        ),
        description="An alert youth stands on a grassy mound holding an upright sword with both hands, looking over his shoulder while winds whip the clouds and trees.",
        upright_interpretation="Sharp curiosity, vibrant intellect, quick-witted observation, and truth-seeking communication.",
        reversed_interpretation="Defensive sarcasm, spreading spiteful gossip, or speaking recklessly without full understanding.",
    ),
    TarotCard(
        id="knight_of_swords",
        name="Knight of Swords",
        name_zh="宝剑骑士",
        arcana=ArcanaType.MINOR,
        number=12,
        suit=Suit.SWORDS,
        element=Element.AIR,
        astrology="Air of Air",
        archetype="The Impetuous Champion / Charging Intellect",
        keywords=CardMeaning(
            upright=["Ambition", "Direct Action", "Fast-thinking", "Driven", "Sharp Intellect", "Courage"],
            reversed=["Aggression", "Recklessness", "Tactlessness", "Burnout", "Hostility"],
        ),
        description="An armor-clad knight charges at full gallop on a white warhorse with drawn sword raised high, racing fearlessly through fierce winds and stormy clouds.",
        upright_interpretation="Relentless mental focus, decisive logical force, and swift determination to conquer challenges.",
        reversed_interpretation="Blunt tactlessness, reckless intellectual arrogance, or running roughshod over the feelings of others.",
    ),
    TarotCard(
        id="queen_of_swords",
        name="Queen of Swords",
        name_zh="宝剑王后",
        arcana=ArcanaType.MINOR,
        number=13,
        suit=Suit.SWORDS,
        element=Element.AIR,
        astrology="Water of Air",
        archetype="The Perceptive Judge / Independent Truth-Teller",
        keywords=CardMeaning(
            upright=["Clarity", "Independence", "Unbiased Judgement", "Clear Boundaries", "Directness", "Wit"],
            reversed=["Cold-hearted", "Bitter", "Hypercritical", "Cruel", "Cynicism"],
        ),
        description="A stern, crowned queen sits on a stone throne adorned with a winged cherub, extending one hand beckoning truth while holding an upright sword high.",
        upright_interpretation="Cut through emotional fog with incisive clarity, honest boundaries, and perceptive discernment.",
        reversed_interpretation="Cold bitterness, severe hypercritical sarcasm, or building defensive emotional walls.",
    ),
    TarotCard(
        id="king_of_swords",
        name="King of Swords",
        name_zh="宝剑国王",
        arcana=ArcanaType.MINOR,
        number=14,
        suit=Suit.SWORDS,
        element=Element.AIR,
        astrology="Fire of Air",
        archetype="The Sovereign Mind / Ethical Authority",
        keywords=CardMeaning(
            upright=["Mental Authority", "Intellectual Power", "Truth", "Justice", "Ethical Leadership", "Logic"],
            reversed=["Tyranny", "Cruelty", "Abuse of Power", "Cold Rigidity", "Dogmatic Control"],
        ),
        description="An authoritative king in robes of blue and purple sits on a stone throne carved with butterflies and crescents, holding an upright sword of state.",
        upright_interpretation="Commanding intellectual authority, objective ethical reasoning, and principled fair-minded leadership.",
        reversed_interpretation="Autocratic tyranny, weaponized intellect, or cold, unfeeling micromanagement devoid of empathy.",
    ),
]
