"""Minor Arcana - Suit of Cups (14 cards) for the Rider-Waite-Smith Tarot Canon."""

from typing import List
from .models import ArcanaType, CardMeaning, Element, Suit, TarotCard

CUPS: List[TarotCard] = [
    TarotCard(
        id="ace_of_cups",
        name="Ace of Cups",
        name_zh="圣杯一",
        arcana=ArcanaType.MINOR,
        number=1,
        suit=Suit.CUPS,
        element=Element.WATER,
        astrology="Root of the Powers of Water",
        archetype="The Fountain of Love",
        keywords=CardMeaning(
            upright=["Love", "New Feelings", "Intuition", "Emotional Awakening", "Spiritual Flow", "Compassion"],
            reversed=["Emotional Drain", "Blocked Intuition", "Heartbreak", "Self-Love Deficit", "Repression"],
        ),
        description="A divine hand offers an ornate golden chalice overflowing with five streams of living water into a lotus pond, while a white dove holding a communion wafer descends into it.",
        upright_interpretation="An outpouring of profound love, new relationships, emotional renewal, and boundless compassionate grace.",
        reversed_interpretation="Feeling emotionally depleted, blocking intuitive feelings, or neglecting self-compassion.",
    ),
    TarotCard(
        id="two_of_cups",
        name="Two of Cups",
        name_zh="圣杯二",
        arcana=ArcanaType.MINOR,
        number=2,
        suit=Suit.CUPS,
        element=Element.WATER,
        astrology="Venus in Cancer",
        archetype="The Sacred Union / Soul Connection",
        keywords=CardMeaning(
            upright=["Unified Love", "Partnership", "Mutual Attraction", "Harmony", "Connection", "Equality"],
            reversed=["Breakup", "Imbalance", "Miscommunication", "Distrust", "Disharmony"],
        ),
        description="A young man and woman exchange golden cups in a pledge of mutual affection beneath the winged lion head of the Caduceus of Hermes.",
        upright_interpretation="Deep mutual bond, harmonious romance, egalitarian partnership, and heartfelt emotional exchange.",
        reversed_interpretation="Misaligned emotional expectations, broken agreements, friction, or relational codependency.",
    ),
    TarotCard(
        id="three_of_cups",
        name="Three of Cups",
        name_zh="圣杯三",
        arcana=ArcanaType.MINOR,
        number=3,
        suit=Suit.CUPS,
        element=Element.WATER,
        astrology="Mercury in Cancer",
        archetype="The Joyous Graces / Sisterhood & Celebration",
        keywords=CardMeaning(
            upright=["Celebration", "Friendship", "Sisterhood", "Community", "Gathering", "Collaboration"],
            reversed=["Gossip", "Isolation", "Overindulgence", "Third-party Interference", "Exclusion"],
        ),
        description="Three women crowned with floral wreaths raise their golden chalices in joyous dance amidst a harvest of grapes, flowers, and gourds.",
        upright_interpretation="Festive celebration with dear friends, joyful reunions, supportive community spirit, and shared happiness.",
        reversed_interpretation="Gossipy cliques, toxic social drama, overindulgent partying, or feeling isolated from peer groups.",
    ),
    TarotCard(
        id="four_of_cups",
        name="Four of Cups",
        name_zh="圣杯四",
        arcana=ArcanaType.MINOR,
        number=4,
        suit=Suit.CUPS,
        element=Element.WATER,
        astrology="Moon in Cancer",
        archetype="The Contemplative Apathy / Boredom",
        keywords=CardMeaning(
            upright=["Apathy", "Contemplation", "Discontent", "Reevaluation", "Boredom", "Missed Offer"],
            reversed=["Renewed Interest", "Seizing Opportunity", "Awakening", "Acceptance", "Gratitude"],
        ),
        description="A seated youth with folded arms sits under a tree contemplating three cups on the grass, seemingly oblivious to a fourth cup offered from a cloud.",
        upright_interpretation="Emotional stagnation, discontent, or introspection causing you to overlook new invitations and gifts right in front of you.",
        reversed_interpretation="Snapping out of apathy, opening eyes to overlooked blessings, and enthusiastically engaging with life again.",
    ),
    TarotCard(
        id="five_of_cups",
        name="Five of Cups",
        name_zh="圣杯五",
        arcana=ArcanaType.MINOR,
        number=5,
        suit=Suit.CUPS,
        element=Element.WATER,
        astrology="Mars in Scorpio",
        archetype="The Grieving Mourner / Regret",
        keywords=CardMeaning(
            upright=["Loss", "Grief", "Regret", "Disappointment", "Sorrow", "Focus on the Negative"],
            reversed=["Acceptance", "Moving On", "Forgiveness", "Healing", "Finding Hope"],
        ),
        description="A black-cloaked figure hangs their head in mourning over three spilled chalices, unaware of two full cups standing upright behind them near a bridge leading to a castle.",
        upright_interpretation="Mourning a bitter disappointment or emotional loss. Remember to look behind you to see what still remains intact.",
        reversed_interpretation="Healing emotional wounds, accepting the past with forgiveness, and crossing the bridge toward renewed hope.",
    ),
    TarotCard(
        id="six_of_cups",
        name="Six of Cups",
        name_zh="圣杯六",
        arcana=ArcanaType.MINOR,
        number=6,
        suit=Suit.CUPS,
        element=Element.WATER,
        astrology="Sun in Scorpio",
        archetype="Childhood Innocence / Nostalgia",
        keywords=CardMeaning(
            upright=["Nostalgia", "Childhood Memories", "Innocence", "Reunion", "Playfulness", "Gentleness"],
            reversed=["Stuck in the Past", "Unrealistic Idealism", "Leaving Childhood", "Moving Forward"],
        ),
        description="In an idyllic courtyard, a boy offers a flower-filled chalice to a younger girl, with four more flower-filled cups in the foreground and a watchful guard in the distance.",
        upright_interpretation="Warm nostalgic reminiscence, kind innocent gestures, rekindled friendships from the past, and playful joy.",
        reversed_interpretation="Living in an idealized past, clinging to obsolete childhood patterns, or facing the demands of emotional maturity.",
    ),
    TarotCard(
        id="seven_of_cups",
        name="Seven of Cups",
        name_zh="圣杯七",
        arcana=ArcanaType.MINOR,
        number=7,
        suit=Suit.CUPS,
        element=Element.WATER,
        astrology="Venus in Scorpio",
        archetype="The Daydreamer / Castle in the Sky",
        keywords=CardMeaning(
            upright=["Choices", "Fantasy", "Illusion", "Wishful Thinking", "Imagination", "Temptation"],
            reversed=["Clarity", "Realism", "Making a Choice", "Disillusionment", "Decisive Action"],
        ),
        description="A shadowy figure in silhouette stands before seven cups emerging from clouds, each filled with various symbolic visions (a snake, castle, jewels, dragon, head, laurel, veiled figure).",
        upright_interpretation="A plethora of options, imaginative fantasies, and seductive temptations. Discern genuine substance from alluring illusions.",
        reversed_interpretation="Cutting through foggy daydreams to make grounded, realistic, and practical choices.",
    ),
    TarotCard(
        id="eight_of_cups",
        name="Eight of Cups",
        name_zh="圣杯八",
        arcana=ArcanaType.MINOR,
        number=8,
        suit=Suit.CUPS,
        element=Element.WATER,
        astrology="Saturn in Pisces",
        archetype="The Spiritual Pilgrim / Leaving Behind",
        keywords=CardMeaning(
            upright=["Walking Away", "Disillusionment", "Spiritual Search", "Abandonment", "Letting Go", "Seeking Higher Truth"],
            reversed=["Fear of Change", "Staying in Bad Situations", "Aimless Wandering", "Avoidance"],
        ),
        description="A cloaked figure with a staff walks away into mountainous terrain under a crescent moon, turning their back on eight neatly stacked golden cups.",
        upright_interpretation="Consciously walking away from an emotionally hollow or unfulfilling situation to seek deeper spiritual meaning.",
        reversed_interpretation="Hesitating to leave a stagnant relationship or job due to fear of the unknown; or wandering aimlessly without a purpose.",
    ),
    TarotCard(
        id="nine_of_cups",
        name="Nine of Cups",
        name_zh="圣杯九",
        arcana=ArcanaType.MINOR,
        number=9,
        suit=Suit.CUPS,
        element=Element.WATER,
        astrology="Jupiter in Pisces",
        archetype="The Wish Fulfilled / Jovial Host",
        keywords=CardMeaning(
            upright=["Satisfaction", "Contentment", "Wish Come True", "Gratitude", "Luxury", "Pleasure"],
            reversed=["Overindulgence", "Smugness", "Unfulfilled Desires", "Greed", "Superficiality"],
        ),
        description="A prosperous, jovial man sits comfortably with folded arms on a wooden bench, smiling proudly before an arched display of nine gleaming golden cups on a blue-draped table.",
        upright_interpretation="The 'Wish Card': Emotional contentment, culinary and sensual pleasures, fulfillment of dreams, and deep satisfaction.",
        reversed_interpretation="Smug vanity, shallow materialism, or discovering that getting what you wished for did not bring genuine inner peace.",
    ),
    TarotCard(
        id="ten_of_cups",
        name="Ten of Cups",
        name_zh="圣杯十",
        arcana=ArcanaType.MINOR,
        number=10,
        suit=Suit.CUPS,
        element=Element.WATER,
        astrology="Mars in Pisces",
        archetype="The Harmonious Family / Rainbow Blessing",
        keywords=CardMeaning(
            upright=["Divine Love", "Family Bliss", "Harmony", "Emotional Fulfillment", "Peace", "Domestic Joy"],
            reversed=["Domestic Strife", "Broken Family", "Disconnection", "Values Conflict", "False Harmony"],
        ),
        description="A loving couple with arms raised in joy stands beside their dancing children before a quaint cottage and river, looking up at a radiant rainbow of ten cups.",
        upright_interpretation="Peak emotional bliss, happy domestic harmony, supportive family ties, and enduring spiritual peace.",
        reversed_interpretation="Family discord, shattered idyllic illusions, or struggles to balance individual desires with familial expectations.",
    ),
    TarotCard(
        id="page_of_cups",
        name="Page of Cups",
        name_zh="圣杯侍从",
        arcana=ArcanaType.MINOR,
        number=11,
        suit=Suit.CUPS,
        element=Element.WATER,
        astrology="Earth of Water",
        archetype="The Gentle Dreamer / Poetic Messenger",
        keywords=CardMeaning(
            upright=["Creative Intuition", "Curiosity", "Sweet Message", "Vulnerability", "Gentle Spirit"],
            reversed=["Emotional Immaturity", "Insecurity", "Creative Insecurity", "Moodiness", "Escapism"],
        ),
        description="A gentle youth dressed in a floral tunic stands by the seashore, holding a golden cup from which a curious fish pops its head to look at him.",
        upright_interpretation="A delightful emotional message, intuitive synchronicity, poetic creativity, and innocent open-heartedness.",
        reversed_interpretation="Childish hypersensitivity, emotional mood swings, or using fantasy to escape harsh everyday obligations.",
    ),
    TarotCard(
        id="knight_of_cups",
        name="Knight of Cups",
        name_zh="圣杯骑士",
        arcana=ArcanaType.MINOR,
        number=12,
        suit=Suit.CUPS,
        element=Element.WATER,
        astrology="Air of Water",
        archetype="The Romantic Poet / Chivalrous Suitor",
        keywords=CardMeaning(
            upright=["Romance", "Charm", "Idealism", "Following the Heart", "Diplomacy", "Grace"],
            reversed=["Overly Emotional", "Unrealistic Idealism", "Manipulation", "Heartbreaker", "Jealousy"],
        ),
        description="A graceful knight in fish-scaled armor rides a calm grey horse across a riverbank, holding forth a golden cup as if offering a poetic toast.",
        upright_interpretation="Pursue your deepest romantic and artistic ideals with charm, grace, and heartfelt sincerity.",
        reversed_interpretation="Fickle romantic escapism, narcissistic charm masking shallow commitment, or overwhelming moodiness.",
    ),
    TarotCard(
        id="queen_of_cups",
        name="Queen of Cups",
        name_zh="圣杯王后",
        arcana=ArcanaType.MINOR,
        number=13,
        suit=Suit.CUPS,
        element=Element.WATER,
        astrology="Water of Water",
        archetype="The Empathetic Healer / Compassionate Queen",
        keywords=CardMeaning(
            upright=["Compassion", "Empathy", "Intuitive Depth", "Emotional Support", "Caring", "Serenity"],
            reversed=["Emotional Dependency", "Martyrdom", "Overly Sensitive", "Smothering", "Insecurity"],
        ),
        description="A queen in ornate robes sits on a sea-throne adorned with mermaids, gazing contemplatively into a closed, elaborate golden chalice with winged cherubs.",
        upright_interpretation="Deep empathetic listening, nurturing emotional wisdom, spiritual tranquility, and psychic intuition.",
        reversed_interpretation="Emotional codependency, becoming drained by others' emotional turmoil, or retreating into hypersensitive moodiness.",
    ),
    TarotCard(
        id="king_of_cups",
        name="King of Cups",
        name_zh="圣杯国王",
        arcana=ArcanaType.MINOR,
        number=14,
        suit=Suit.CUPS,
        element=Element.WATER,
        astrology="Fire of Water",
        archetype="The Master of Emotions / Wise Counselor",
        keywords=CardMeaning(
            upright=["Emotional Balance", "Compassionate Leadership", "Diplomacy", "Wisdom", "Devotion", "Calm"],
            reversed=["Emotional Manipulation", "Volatility", "Coldness", "Moodiness", "Turbulence"],
        ),
        description="A king in turquoise and blue robes sits upon a stone throne floating atop turbulent seas, holding a lotus scepter and a golden cup while a ship and dolphin leap behind him.",
        upright_interpretation="Emotional mastery and calm stability amidst life's stormy seas; leadership guided by empathy and wisdom.",
        reversed_interpretation="Passive-aggressive manipulation, repressed emotional turmoil erupting into outbursts, or cold detachment.",
    ),
]
