"""Minor Arcana - Suit of Wands (14 cards) for the Rider-Waite-Smith Tarot Canon."""

from typing import List
from .models import ArcanaType, CardMeaning, Element, Suit, TarotCard

WANDS: List[TarotCard] = [
    TarotCard(
        id="ace_of_wands",
        name="Ace of Wands",
        name_zh="权杖一",
        arcana=ArcanaType.MINOR,
        number=1,
        suit=Suit.WANDS,
        element=Element.FIRE,
        astrology="Root of the Powers of Fire",
        archetype="The Spark of Inspiration",
        keywords=CardMeaning(
            upright=["Inspiration", "Creative Spark", "New Passion", "Potential", "Drive", "Enthusiasm"],
            reversed=["Lack of Direction", "Delays", "Creative Block", "Missed Opportunity", "Hesitation"],
        ),
        description="A divine hand emerges from a cloud grasping a sprouting wooden wand, with green leaves floating against a landscape of hills and a distant castle.",
        upright_interpretation="A potent surge of creative drive, fresh passion, and entrepreneurial spark. Seize the momentum boldly.",
        reversed_interpretation="Creative frustration, lack of direction, or difficulty turning a fiery spark into sustained action.",
    ),
    TarotCard(
        id="two_of_wands",
        name="Two of Wands",
        name_zh="权杖二",
        arcana=ArcanaType.MINOR,
        number=2,
        suit=Suit.WANDS,
        element=Element.FIRE,
        astrology="Mars in Aries",
        archetype="The Visionary Planner",
        keywords=CardMeaning(
            upright=["Planning", "Future Vision", "Progress", "Decisions", "Discovery", "Expansion"],
            reversed=["Fear of Unknown", "Lack of Planning", "Overanalyzing", "Playing Safe", "Restlessness"],
        ),
        description="A nobleman in a red cloak stands on a castle battlement holding a small globe in one hand and a staff in the other, gazing out over the ocean.",
        upright_interpretation="Broadening horizons through structured forward planning and deliberate strategic decisions.",
        reversed_interpretation="Fear of stepping outside comfort zones or hesitating to enact long-term travel and expansion plans.",
    ),
    TarotCard(
        id="three_of_wands",
        name="Three of Wands",
        name_zh="权杖三",
        arcana=ArcanaType.MINOR,
        number=3,
        suit=Suit.WANDS,
        element=Element.FIRE,
        astrology="Sun in Aries",
        archetype="The Far-Sighted Merchant / Overseas Expansion",
        keywords=CardMeaning(
            upright=["Expansion", "Foresight", "Overseas Opportunities", "Momentum", "Confidence", "Progress"],
            reversed=["Delays", "Obstacles", "Frustration", "Disappointment in Results", "Myopia"],
        ),
        description="A man stands on a cliff with his back turned, grasping one of three firmly planted staves as ships sail across the sea toward distant shores.",
        upright_interpretation="Your plans are in motion and early ships are sailing into port. Expect rewarding expansion and overseas opportunities.",
        reversed_interpretation="Unforeseen delays, logistics bottlenecks, or unrealistic expectations causing progress to stall.",
    ),
    TarotCard(
        id="four_of_wands",
        name="Four of Wands",
        name_zh="权杖四",
        arcana=ArcanaType.MINOR,
        number=4,
        suit=Suit.WANDS,
        element=Element.FIRE,
        astrology="Venus in Aries",
        archetype="The Home Celebration / Harmony",
        keywords=CardMeaning(
            upright=["Celebration", "Homecoming", "Harmony", "Community", "Milestones", "Domestic Peace"],
            reversed=["Tension at Home", "Cancelled Event", "Lack of Support", "Transient Instability"],
        ),
        description="Two figures hold bouquets beneath a large floral bower supported by four crystal-topped staves, with a joyous manor house in the background.",
        upright_interpretation="Joyous domestic celebration, welcoming community milestones, and a secure foundation of harmony.",
        reversed_interpretation="Domestic disharmony, postponed family celebrations, or feeling out of place within one's community.",
    ),
    TarotCard(
        id="five_of_wands",
        name="Five of Wands",
        name_zh="权杖五",
        arcana=ArcanaType.MINOR,
        number=5,
        suit=Suit.WANDS,
        element=Element.FIRE,
        astrology="Saturn in Leo",
        archetype="The Friendly Rivalry / Chaos",
        keywords=CardMeaning(
            upright=["Conflict", "Competition", "Disagreements", "Rivalry", "Tension", "Struggle"],
            reversed=["Conflict Avoidance", "Resolution", "Compromise", "Harmony Restored", "Burnout"],
        ),
        description="Five youths engage in a chaotic mock battle, clashing their wooden staves in energetic competition against a clear sky.",
        upright_interpretation="Healthy competition or petty conflicting opinions requiring patience, active communication, and sportsmanship.",
        reversed_interpretation="Escaping or resolving unproductive friction, seeking harmonious mediation, or feeling exhausted by conflict.",
    ),
    TarotCard(
        id="six_of_wands",
        name="Six of Wands",
        name_zh="权杖六",
        arcana=ArcanaType.MINOR,
        number=6,
        suit=Suit.WANDS,
        element=Element.FIRE,
        astrology="Jupiter in Leo",
        archetype="The Victorious Hero's Return",
        keywords=CardMeaning(
            upright=["Victory", "Success", "Public Recognition", "Pride", "Acclaim", "Triumph"],
            reversed=["Egoism", "Fall from Grace", "Lack of Recognition", "Disgrace", "Self-doubt"],
        ),
        description="A laurel-crowned horseman rides a white steed through a cheering crowd, holding a wand topped with a victory wreath.",
        upright_interpretation="Public triumph, well-deserved recognition, praise, and validation for your hard work and perseverance.",
        reversed_interpretation="Wounded pride, lack of expected public appreciation, or excessive arrogance leading to a fall from grace.",
    ),
    TarotCard(
        id="seven_of_wands",
        name="Seven of Wands",
        name_zh="权杖七",
        arcana=ArcanaType.MINOR,
        number=7,
        suit=Suit.WANDS,
        element=Element.FIRE,
        astrology="Mars in Leo",
        archetype="The Defiant Defender",
        keywords=CardMeaning(
            upright=["Defensiveness", "Courage", "Standing Ground", "Perseverance", "Territory Defense", "Resilience"],
            reversed=["Overwhelmed", "Giving Up", "Exhaustion", "Defeatism", "Vulnerability"],
        ),
        description="A determined man stands atop a hill defending his high ground with a stout staff against six attacking staves rising from below.",
        upright_interpretation="Hold your ground against competition or criticism. Your higher vantage point and conviction give you the advantage.",
        reversed_interpretation="Feeling besieged and worn out by relentless challenges. Know when to ask for backup or reconsider your battle lines.",
    ),
    TarotCard(
        id="eight_of_wands",
        name="Eight of Wands",
        name_zh="权杖八",
        arcana=ArcanaType.MINOR,
        number=8,
        suit=Suit.WANDS,
        element=Element.FIRE,
        astrology="Mercury in Sagittarius",
        archetype="Swift Movement / Rapid Messages",
        keywords=CardMeaning(
            upright=["Speed", "Rapid Action", "Movement", "Air Travel", "Fast News", "Alignment"],
            reversed=["Delays", "Frustration", "Hasty Decisions", "Miscommunication", "Slowing Down"],
        ),
        description="Eight sprouted wooden staves fly through clear open air at high speed over a peaceful green valley with a flowing river.",
        upright_interpretation="Events accelerate rapidly toward resolution. Expect swift messages, prompt communication, and high momentum.",
        reversed_interpretation="Unavoidable delays, misdirected communication, or acting so recklessly fast that mistakes are made.",
    ),
    TarotCard(
        id="nine_of_wands",
        name="Nine of Wands",
        name_zh="权杖九",
        arcana=ArcanaType.MINOR,
        number=9,
        suit=Suit.WANDS,
        element=Element.FIRE,
        astrology="Moon in Sagittarius",
        archetype="The Battle-Hardened Sentinel",
        keywords=CardMeaning(
            upright=["Resilience", "Grit", "Last Stand", "Persistence", "Boundaries", "Endurance"],
            reversed=["Exhaustion", "Paranoia", "Giving Up", "Defensive Overkill", "Refusing Help"],
        ),
        description="A bandaged, battle-weary soldier leans vigilantly against a staff, backed by eight upright staves arranged as a defensive barricade.",
        upright_interpretation="You are close to the finish line despite battle fatigue. Muster your remaining stamina for this final test.",
        reversed_interpretation="Defensive paranoia, chronic burnout, or stubborn refusal to lower rigid guards and receive help.",
    ),
    TarotCard(
        id="ten_of_wands",
        name="Ten of Wands",
        name_zh="权杖十",
        arcana=ArcanaType.MINOR,
        number=10,
        suit=Suit.WANDS,
        element=Element.FIRE,
        astrology="Saturn in Sagittarius",
        archetype="The Overburdened Carrier",
        keywords=CardMeaning(
            upright=["Burden", "Extra Responsibility", "Hard Work", "Stress", "Obligation", "End of Journey"],
            reversed=["Burnout", "Delegating", "Dropping Burdens", "Crushing Pressure", "Overwhelmed"],
        ),
        description="A figure bends forward under the heavy weight of ten heavy wooden staves, trudging slowly toward a town in the distance.",
        upright_interpretation="Carrying an excessive load of duties and responsibilities. The destination is near, but delegation is crucial.",
        reversed_interpretation="Relinquishing unsustainable burdens, learning to say no, or breaking down under crushing over-commitment.",
    ),
    TarotCard(
        id="page_of_wands",
        name="Page of Wands",
        name_zh="权杖侍从",
        arcana=ArcanaType.MINOR,
        number=11,
        suit=Suit.WANDS,
        element=Element.FIRE,
        astrology="Earth of Fire",
        archetype="The Enthusiastic Messenger / Explorer",
        keywords=CardMeaning(
            upright=["Enthusiasm", "Exploration", "Good News", "Curiosity", "Fresh Ideas", "Creative Spark"],
            reversed=["Lack of Follow-through", "Procrastination", "Bad News", "Impatience", "Flightiness"],
        ),
        description="A youth in a salamander-patterned tunic stands in a desert holding a tall budding staff, gazing up at its flowering top.",
        upright_interpretation="A joyful message or burst of creative curiosity invites you to explore new adventurous territories.",
        reversed_interpretation="Childish impatience, unchannelled energy fizzling out without execution, or disappointing news.",
    ),
    TarotCard(
        id="knight_of_wands",
        name="Knight of Wands",
        name_zh="权杖骑士",
        arcana=ArcanaType.MINOR,
        number=12,
        suit=Suit.WANDS,
        element=Element.FIRE,
        astrology="Air of Fire",
        archetype="The Daring Adventurer / Fiery Champion",
        keywords=CardMeaning(
            upright=["Energy", "Passion", "Action", "Adventure", "Impulsiveness", "Charisma"],
            reversed=["Recklessness", "Hastiness", "Hot Temper", "Volatile Energy", "Scattered Focus"],
        ),
        description="An energetic knight in full armor and a salamander-emblazoned cloak gallops across the desert on a rearing chestnut stallion, holding a staff aloft.",
        upright_interpretation="High energy, bold charismatic action, and fearless pursuit of ambitious goals.",
        reversed_interpretation="Hot-headed recklessness, aggressive impatience, or rushing into projects without considering long-term sustainability.",
    ),
    TarotCard(
        id="queen_of_wands",
        name="Queen of Wands",
        name_zh="权杖王后",
        arcana=ArcanaType.MINOR,
        number=13,
        suit=Suit.WANDS,
        element=Element.FIRE,
        astrology="Water of Fire",
        archetype="The Radiant Muse / Confident Leader",
        keywords=CardMeaning(
            upright=["Confidence", "Courage", "Independence", "Vibrancy", "Warmth", "Charisma"],
            reversed=["Jealousy", "Insecurity", "Demanding", "Selfishness", "Temperamental"],
        ),
        description="A confident, radiant queen sits on a lion-decorated throne holding a staff and a sunflower, with a friendly black cat at her feet.",
        upright_interpretation="Exude magnetic warmth, fierce creative independence, and confident leadership.",
        reversed_interpretation="Insecurity leading to manipulative jealousy, temper tantrums, or demanding excessive attention.",
    ),
    TarotCard(
        id="king_of_wands",
        name="King of Wands",
        name_zh="权杖国王",
        arcana=ArcanaType.MINOR,
        number=14,
        suit=Suit.WANDS,
        element=Element.FIRE,
        astrology="Fire of Fire",
        archetype="The Inspiring Leader / Visionary Master",
        keywords=CardMeaning(
            upright=["Leadership", "Vision", "Entrepreneurship", "Honour", "Charisma", "Inspiration"],
            reversed=["Impulsiveness", "Tyranny", "Arrogance", "High Expectations", "Overbearing"],
        ),
        description="A crowned ruler in robes patterned with lions and ouroboros salamanders sits on his lion throne holding a budding staff with authority.",
        upright_interpretation="Lead with grand visionary authority, big-picture thinking, and charismatic entrepreneurial spirit.",
        reversed_interpretation="Overbearing arrogance, authoritarian dominance, or having grand ideas without the patience to manage execution details.",
    ),
]
