"""Minor Arcana - Suit of Pentacles (14 cards) for the Rider-Waite-Smith Tarot Canon."""

from typing import List
from .models import ArcanaType, CardMeaning, Element, Suit, TarotCard

PENTACLES: List[TarotCard] = [
    TarotCard(
        id="ace_of_pentacles",
        name="Ace of Pentacles",
        name_zh="星币一",
        arcana=ArcanaType.MINOR,
        number=1,
        suit=Suit.PENTACLES,
        element=Element.EARTH,
        astrology="Root of the Powers of Earth",
        archetype="The Seed of Prosperity / Material Gift",
        keywords=CardMeaning(
            upright=["Opportunity", "Prosperity", "New Venture", "Abundance", "Manifestation", "Financial Security"],
            reversed=["Lost Opportunity", "Financial Insecurity", "Poor Investment", "Greed", "Scarcity Mindset"],
        ),
        description="A divine hand emerges from a cloud offering a large golden coin embossed with a pentagram, floating above a blooming garden and archway looking onto mountains.",
        upright_interpretation="A solid, tangible opportunity for wealth, career growth, health improvement, and physical manifestation.",
        reversed_interpretation="A missed financial or career opportunity, reckless spending, or lack of grounding in practical realities.",
    ),
    TarotCard(
        id="two_of_pentacles",
        name="Two of Pentacles",
        name_zh="星币二",
        arcana=ArcanaType.MINOR,
        number=2,
        suit=Suit.PENTACLES,
        element=Element.EARTH,
        astrology="Jupiter in Capricorn",
        archetype="The Juggler of Life / Dynamic Balance",
        keywords=CardMeaning(
            upright=["Balance", "Adaptability", "Time Management", "Priorities", "Juggling", "Flexibility"],
            reversed=["Overwhelmed", "Disorganization", "Financial Stress", "Dropped Balls", "Imbalance"],
        ),
        description="A nimble youth in colorful garb juggles two golden coins connected by an infinity loop, while sailing ships ride rolling ocean waves in the background.",
        upright_interpretation="Gracefully balancing multiple priorities, finances, or work demands with lighthearted flexibility.",
        reversed_interpretation="Overextended schedule, dropped responsibilities, and financial mismanagement creating chaotic stress.",
    ),
    TarotCard(
        id="three_of_pentacles",
        name="Three of Pentacles",
        name_zh="星币三",
        arcana=ArcanaType.MINOR,
        number=3,
        suit=Suit.PENTACLES,
        element=Element.EARTH,
        astrology="Mars in Capricorn",
        archetype="The Master Craftsman / Teamwork & Mastery",
        keywords=CardMeaning(
            upright=["Teamwork", "Collaboration", "Craftsmanship", "Mastery", "Competence", "Quality"],
            reversed=["Lack of Cohesion", "Poor Quality", "Ego Clashes", "Unskilled Work", "Misalignment"],
        ),
        description="A stone mason works upon the archway of a cathedral, conferring attentively with a monk and an architect holding architectural blueprints.",
        upright_interpretation="High craftsmanship and successful collaboration where diverse skills unite to build something enduring.",
        reversed_interpretation="Disorganized teamwork, ego friction between contributors, or subpar workmanship compromising quality.",
    ),
    TarotCard(
        id="four_of_pentacles",
        name="Four of Pentacles",
        name_zh="星币四",
        arcana=ArcanaType.MINOR,
        number=4,
        suit=Suit.PENTACLES,
        element=Element.EARTH,
        astrology="Sun in Capricorn",
        archetype="The Miser / Guarded Security",
        keywords=CardMeaning(
            upright=["Security", "Frugality", "Control", "Conservation", "Possessiveness", "Boundaries"],
            reversed=["Greed", "Materialism", "Fear of Loss", "Letting Go", "Financial Recklessness"],
        ),
        description="A crowned man sits firmly gripping four coins: one on his head, one clasped tightly in his arms, and two pinned beneath his feet overlooking a city.",
        upright_interpretation="Prudent financial conservation and establishing solid security, though risking emotional hoarding and rigidity.",
        reversed_interpretation="Letting go of obsessive control and scarcity fears; or at worse, wasteful spending and insecurity.",
    ),
    TarotCard(
        id="five_of_pentacles",
        name="Five of Pentacles",
        name_zh="星币五",
        arcana=ArcanaType.MINOR,
        number=5,
        suit=Suit.PENTACLES,
        element=Element.EARTH,
        astrology="Mercury in Taurus",
        archetype="The Outcasts in the Snow / Hardship",
        keywords=CardMeaning(
            upright=["Hardship", "Financial Loss", "Poverty", "Isolation", "Worry", "Exclusion"],
            reversed=["Recovery", "Charity", "Improving Finances", "Finding Shelter", "End of Hardship"],
        ),
        description="Two impoverished figures in tattered clothes trudge through heavy snow past the glowing stained-glass window of a sanctuary church.",
        upright_interpretation="Experiencing temporary financial or emotional hardship. Look up to notice available sanctuary and community support.",
        reversed_interpretation="Recovery from financial destitution, emerging into security, and welcoming newly found assistance.",
    ),
    TarotCard(
        id="six_of_pentacles",
        name="Six of Pentacles",
        name_zh="星币六",
        arcana=ArcanaType.MINOR,
        number=6,
        suit=Suit.PENTACLES,
        element=Element.EARTH,
        astrology="Moon in Taurus",
        archetype="The Generous Benefactor / Giving & Receiving",
        keywords=CardMeaning(
            upright=["Generosity", "Charity", "Sharing Wealth", "Fairness", "Giving and Receiving", "Support"],
            reversed=["Strings Attached", "Debt", "Inequality", "One-sided Charity", "Selfishness"],
        ),
        description="A prosperous merchant in rich robes holds scales of balance in one hand while bestowing coins to kneeling supplicants.",
        upright_interpretation="Generous sharing of resources, reciprocal kindness, philanthropy, and restoring balance through aid.",
        reversed_interpretation="Conditional charity with ulterior strings attached, power imbalances, or feeling taken advantage of financially.",
    ),
    TarotCard(
        id="seven_of_pentacles",
        name="Seven of Pentacles",
        name_zh="星币七",
        arcana=ArcanaType.MINOR,
        number=7,
        suit=Suit.PENTACLES,
        element=Element.EARTH,
        astrology="Saturn in Taurus",
        archetype="The Patient Harvester / Evaluation",
        keywords=CardMeaning(
            upright=["Patience", "Long-term View", "Investment", "Harvest", "Evaluation", "Hard Work"],
            reversed=["Impatience", "Wasted Effort", "Lack of Reward", "Poor Returns", "Frustration"],
        ),
        description="A farmer rests on his spade, gazing thoughtfully at a lush crop of vines bearing seven golden pentacles.",
        upright_interpretation="Patience while investments mature; taking a reflective pause to evaluate progress toward long-term goals.",
        reversed_interpretation="Impatience for instant results, neglecting tending to crops, or realizing a project yields poor return on investment.",
    ),
    TarotCard(
        id="eight_of_pentacles",
        name="Eight of Pentacles",
        name_zh="星币八",
        arcana=ArcanaType.MINOR,
        number=8,
        suit=Suit.PENTACLES,
        element=Element.EARTH,
        astrology="Sun in Virgo",
        archetype="The Dedicated Apprentice / Mastery",
        keywords=CardMeaning(
            upright=["Apprenticeship", "Diligence", "Skill Development", "Craftsmanship", "Detail-oriented", "Repetition"],
            reversed=["Perfectionism", "Lack of Ambition", "Careless Work", "Monotony", "Shortcuts"],
        ),
        description="An artisan carves intricate pentagrams into golden coins at his workbench, with six completed coins mounted neatly on a post and another on the ground.",
        upright_interpretation="Dedicated focus on refining your craft, developing valuable new skills, and continuous disciplined improvement.",
        reversed_interpretation="Tedious monotony, sloppy cutting of corners, or paralyzing perfectionism stifling productive output.",
    ),
    TarotCard(
        id="nine_of_pentacles",
        name="Nine of Pentacles",
        name_zh="星币九",
        arcana=ArcanaType.MINOR,
        number=9,
        suit=Suit.PENTACLES,
        element=Element.EARTH,
        astrology="Venus in Virgo",
        archetype="The Cultivated Gentlewoman / Self-Sufficiency",
        keywords=CardMeaning(
            upright=["Abundance", "Self-Sufficiency", "Luxury", "Elegance", "Financial Independence", "Leisure"],
            reversed=["Overspending", "Superficiality", "Financial Dependency", "Isolation", "Workaholic"],
        ),
        description="An elegant woman in rich gold-embroidered robes strolls through a vineyard laden with ripe grapes and golden coins, with a hooded falcon perched on her gloved hand.",
        upright_interpretation="Graceful financial independence, self-sufficient abundance, refined taste, and savoring the fruits of your labor.",
        reversed_interpretation="Living beyond one's means to maintain appearances, emotional isolation amidst luxury, or financial dependency.",
    ),
    TarotCard(
        id="ten_of_pentacles",
        name="Ten of Pentacles",
        name_zh="星币十",
        arcana=ArcanaType.MINOR,
        number=10,
        suit=Suit.PENTACLES,
        element=Element.EARTH,
        astrology="Mercury in Virgo",
        archetype="The Patriarch & Dynasty / Enduring Legacy",
        keywords=CardMeaning(
            upright=["Wealth", "Legacy", "Family Heritage", "Long-term Security", "Tradition", "Establishment"],
            reversed=["Financial Dispute", "Family Feud", "Loss of Inheritance", "Broken Traditions", "Instability"],
        ),
        description="Three generations of family and pet hounds gather in the arched courtyard of an ancestral estate, overlaid with ten golden coins arranged in the Tree of Life pattern.",
        upright_interpretation="Generational wealth, enduring family legacy, deep financial permanence, and enjoying long-term material security.",
        reversed_interpretation="Inheritance squabbles, family financial friction, loss of estate value, or burdens of restrictive lineage traditions.",
    ),
    TarotCard(
        id="page_of_pentacles",
        name="Page of Pentacles",
        name_zh="星币侍从",
        arcana=ArcanaType.MINOR,
        number=11,
        suit=Suit.PENTACLES,
        element=Element.EARTH,
        astrology="Earth of Earth",
        archetype="The Studious Scholar / Pragmatic Apprentice",
        keywords=CardMeaning(
            upright=["Ambition", "Desire to Learn", "Practical Opportunity", "Groundedness", "Loyalty", "Thrift"],
            reversed=["Lack of Progress", "Procrastination", "Short-term Thinking", "Irresponsibility", "Daydreaming"],
        ),
        description="A young scholar stands in a flowering green meadow, gazing intently and reverently at a single golden coin held delicately in both hands.",
        upright_interpretation="A grounded thirst for knowledge, practical business or career opportunity, and establishing solid foundations.",
        reversed_interpretation="Procrastination on studies or financial duties, lack of practical follow-through, or unrealistic dreaming without groundwork.",
    ),
    TarotCard(
        id="knight_of_pentacles",
        name="Knight of Pentacles",
        name_zh="星币骑士",
        arcana=ArcanaType.MINOR,
        number=12,
        suit=Suit.PENTACLES,
        element=Element.EARTH,
        astrology="Air of Earth",
        archetype="The Steadfast Worker / Methodical Guardian",
        keywords=CardMeaning(
            upright=["Efficiency", "Routine", "Conservatism", "Methodical", "Hard Work", "Reliability"],
            reversed=["Stubbornness", "Laziness", "Boring Routine", "Obsessive Perfectionism", "Stagnation"],
        ),
        description="A sturdy knight in full plate armor sits patiently atop a heavy black plow horse in a tilled field, carefully examining a golden coin held in hand.",
        upright_interpretation="Steadfast dedication, methodical consistency, tireless work ethic, and absolute reliability.",
        reversed_interpretation="Rigid stubbornness, being trapped in a deadening rut, or neglecting bigger horizons due to excessive routine.",
    ),
    TarotCard(
        id="queen_of_pentacles",
        name="Queen of Pentacles",
        name_zh="星币王后",
        arcana=ArcanaType.MINOR,
        number=13,
        suit=Suit.PENTACLES,
        element=Element.EARTH,
        astrology="Water of Earth",
        archetype="The Earth Mother / Resourceful Homemaker",
        keywords=CardMeaning(
            upright=["Nurturing", "Practicality", "Financial Security", "Resourcefulness", "Sensuality", "Abundance"],
            reversed=["Work-Life Imbalance", "Smothering", "Material Insecurity", "Self-Neglect", "Greed"],
        ),
        description="A regal queen crowned with flowers sits on an ornate stone throne decorated with cherubs, beasts, and fruit, cradling a golden coin while a rabbit hops in the flowering grass.",
        upright_interpretation="Warm, down-to-earth practicality, generous nurturing, financial acumen, and creating a comfortable, welcoming sanctuary.",
        reversed_interpretation="Financial anxiety despite having enough, work-life burnout, or neglecting personal wellbeing while fussing over others.",
    ),
    TarotCard(
        id="king_of_pentacles",
        name="King of Pentacles",
        name_zh="星币国王",
        arcana=ArcanaType.MINOR,
        number=14,
        suit=Suit.PENTACLES,
        element=Element.EARTH,
        astrology="Fire of Earth",
        archetype="The Master of Enterprise / Lord of Wealth",
        keywords=CardMeaning(
            upright=["Wealth", "Business Acumen", "Abundance", "Discipline", "Security", "Leadership"],
            reversed=["Greed", "Materialistic Obsession", "Bad Financial Decisions", "Bribery", "Stubbornness"],
        ),
        description="A powerful king in luxurious robes patterned with ripe grapevines sits on a throne carved with bulls' heads, holding a golden scepter and resting a hand on a pentacle before a castle.",
        upright_interpretation="Peak business acumen, tangible abundance, enduring material empire, and generous paternal leadership.",
        reversed_interpretation="Greedy materialism, corrupt financial dealings, stubborn penny-pinching, or defining self-worth strictly by wealth.",
    ),
]
