"""Major Arcana (22 cards) for the Rider-Waite-Smith Tarot Canon."""

from typing import List
from .models import ArcanaType, CardMeaning, Element, TarotCard

MAJOR_ARCANA: List[TarotCard] = [
    TarotCard(
        id="the_fool",
        name="The Fool",
        name_zh="愚者",
        arcana=ArcanaType.MAJOR,
        number=0,
        element=Element.AIR,
        astrology="Uranus",
        archetype="The Divine Innocent / The Wanderer",
        keywords=CardMeaning(
            upright=["Beginnings", "Innocence", "Spontaneity", "Free Spirit", "Leap of Faith", "Optimism"],
            reversed=["Recklessness", "Risk-taking", "Foolishness", "Naivety", "Hesitation", "Bad Decisions"],
        ),
        description="A young traveler stands on the edge of a cliff, looking into the sky, accompanied by a small white dog and carrying a white rose and a light satchel.",
        upright_interpretation="Embrace new beginnings with an open heart. Take a leap of faith into the unknown, trusting your inner purity and potential.",
        reversed_interpretation="Beware of impulsive recklessness or disregard for real consequences. Alternatively, fear of taking risks may be stalling your growth.",
    ),
    TarotCard(
        id="the_magician",
        name="The Magician",
        name_zh="魔术师",
        arcana=ArcanaType.MAJOR,
        number=1,
        element=Element.AIR,
        astrology="Mercury",
        archetype="The Creator / The Conduit",
        keywords=CardMeaning(
            upright=["Manifestation", "Resourcefulness", "Power", "Inspired Action", "Skill", "Willpower"],
            reversed=["Manipulation", "Poor Planning", "Untapped Talents", "Trickery", "Wasted Potential"],
        ),
        description="A figure points one hand upward with a wand and one downward to the earth, surrounded by flowers with the four suit symbols laid before him on a table and an infinity symbol above his head.",
        upright_interpretation="You have all the necessary tools and power to manifest your desires into reality. Align intention, action, and concentration.",
        reversed_interpretation="Watch out for deceptive tactics, illusions, or manipulative tendencies. Ensure your inner resources are channeled constructively.",
    ),
    TarotCard(
        id="the_high_priestess",
        name="The High Priestess",
        name_zh="女祭司",
        arcana=ArcanaType.MAJOR,
        number=2,
        element=Element.WATER,
        astrology="Moon",
        archetype="The Intuitive / Keeper of the Subconscious",
        keywords=CardMeaning(
            upright=["Intuition", "Sacred Knowledge", "Divine Feminine", "Subconscious", "Mystery", "Inner Voice"],
            reversed=["Secrets", "Disconnected from Intuition", "Withdrawal", "Surface Level", "Repression"],
        ),
        description="A serene priestess sits between the twin pillars of Boaz (dark) and Jachin (light), holding the Torah scroll with a crescent moon at her feet and a pomegranate veil behind her.",
        upright_interpretation="Trust your deep intuition and look beyond the surface. Answers lie within the stillness of your subconscious mind.",
        reversed_interpretation="You may be ignoring your inner voice or hidden secrets may be causing mistrust. Reconnect with your spiritual sanctuary.",
    ),
    TarotCard(
        id="the_empress",
        name="The Empress",
        name_zh="皇后",
        arcana=ArcanaType.MAJOR,
        number=3,
        element=Element.EARTH,
        astrology="Venus",
        archetype="The Great Mother / The Nurturer",
        keywords=CardMeaning(
            upright=["Fertility", "Abundance", "Nurturing", "Creativity", "Nature", "Sensuality"],
            reversed=["Creative Block", "Dependence", "Smothering", "Neglect", "Emptiness", "Insecurity"],
        ),
        description="A radiant woman crowned with twelve stars sits comfortably in lush nature beside a flowing waterfall and a field of ripe wheat.",
        upright_interpretation="Abundance, growth, and fruitful creativity surround you. Nurture your ideas and relish the sensory beauty of life.",
        reversed_interpretation="Guard against over-dependence, over-nurturing (smothering), or creative stagnation. Attend to your self-care needs.",
    ),
    TarotCard(
        id="the_emperor",
        name="The Emperor",
        name_zh="皇帝",
        arcana=ArcanaType.MAJOR,
        number=4,
        element=Element.FIRE,
        astrology="Aries",
        archetype="The Father / The Sovereign",
        keywords=CardMeaning(
            upright=["Authority", "Structure", "Stability", "Leadership", "Protection", "Discipline"],
            reversed=["Tyranny", "Rigidity", "Lack of Control", "Domination", "Chaos", "Inflexibility"],
        ),
        description="A stern, bearded ruler sits on a stone throne carved with ram heads, holding an ankh scepter and a globe against a backdrop of barren mountains.",
        upright_interpretation="Establish clear boundaries, systems, and structured leadership. Master your domain through discipline and rational authority.",
        reversed_interpretation="Excessive control, micromanagement, or stubborn rigidity creates friction. Alternatively, a breakdown of structure requires rebuilding order.",
    ),
    TarotCard(
        id="the_hierophant",
        name="The Hierophant",
        name_zh="教皇",
        arcana=ArcanaType.MAJOR,
        number=5,
        element=Element.EARTH,
        astrology="Taurus",
        archetype="The Teacher / The High Priest",
        keywords=CardMeaning(
            upright=["Tradition", "Spiritual Wisdom", "Conformity", "Institutions", "Belief Systems", "Mentorship"],
            reversed=["Rebellion", "Subversiveness", "New Beliefs", "Dogma", "Unconventional Lifestyle"],
        ),
        description="A spiritual leader sits between pillars of a sacred temple wearing a triple crown, delivering blessings to two kneeling acolytes with crossed keys at his feet.",
        upright_interpretation="Seek wisdom within established traditions, formal education, or trusted spiritual mentors. Group consensus provides safety.",
        reversed_interpretation="Question outdated dogma and dogma-driven orthodoxy. It may be time to forge your own authentic spiritual and moral path.",
    ),
    TarotCard(
        id="the_lovers",
        name="The Lovers",
        name_zh="恋人",
        arcana=ArcanaType.MAJOR,
        number=6,
        element=Element.AIR,
        astrology="Gemini",
        archetype="The Anima & Animus / Divine Union",
        keywords=CardMeaning(
            upright=["Love", "Harmony", "Relationships", "Values Alignment", "Choice", "Duality"],
            reversed=["Disharmony", "Imbalance", "Misaligned Values", "Indecision", "Conflict"],
        ),
        description="An angel (Raphael) blesses an open, unclothed man and woman standing beneath the Tree of Life and the Tree of Knowledge of Good and Evil with a volcano in the distance.",
        upright_interpretation="Deep soulful connection, profound choices based on personal values, and the integration of complementary forces.",
        reversed_interpretation="Conflict in core values, difficulty in making decisive moral commitments, or relational tension and miscommunication.",
    ),
    TarotCard(
        id="the_chariot",
        name="The Chariot",
        name_zh="战车",
        arcana=ArcanaType.MAJOR,
        number=7,
        element=Element.WATER,
        astrology="Cancer",
        archetype="The Victorious Hero",
        keywords=CardMeaning(
            upright=["Control", "Willpower", "Success", "Determination", "Overcoming Obstacles", "Focus"],
            reversed=["Lack of Control", "Aggression", "Obstacles", "Powerlessness", "Directionless"],
        ),
        description="An armor-clad prince stands within a chariot beneath a star-canopied pavilion, steering two opposing sphinxes (black and white) with pure willpower.",
        upright_interpretation="Harness opposing forces through unwavering determination and focused intent to achieve triumph over adversity.",
        reversed_interpretation="Loss of control or reckless momentum leading to collisions. Step on the brakes and re-align internal motivation before charging ahead.",
    ),
    TarotCard(
        id="strength",
        name="Strength",
        name_zh="力量",
        arcana=ArcanaType.MAJOR,
        number=8,
        element=Element.FIRE,
        astrology="Leo",
        archetype="Gentle Mastery / Compassion",
        keywords=CardMeaning(
            upright=["Courage", "Persuasion", "Influence", "Compassion", "Patience", "Inner Fortitude"],
            reversed=["Self-doubt", "Weakness", "Insecurity", "Raw Emotion", "Vulnerability"],
        ),
        description="A serene woman crowned with flowers and an infinity symbol gently strokes the jaws of a fierce lion, subduing it without force.",
        upright_interpretation="True power comes from gentleness, inner calm, and compassionate self-mastery rather than brute coercion.",
        reversed_interpretation="Internal self-doubt, raw animal impulses overcoming reason, or feeling physically or emotionally drained.",
    ),
    TarotCard(
        id="the_hermit",
        name="The Hermit",
        name_zh="隐士",
        arcana=ArcanaType.MAJOR,
        number=9,
        element=Element.EARTH,
        astrology="Virgo",
        archetype="The Wise Old Man / The Solitary Seeker",
        keywords=CardMeaning(
            upright=["Soul Searching", "Introspection", "Solitude", "Inner Guidance", "Wisdom", "Prudence"],
            reversed=["Isolation", "Loneliness", "Withdrawal", "Rejection of Wisdom", "Paranoia"],
        ),
        description="An old hooded sage stands atop a snowy peak, holding a staff in one hand and a lantern containing a glowing six-pointed star in the other.",
        upright_interpretation="Withdraw from external noise to seek solitary illumination and contemplative truth within your own inner landscape.",
        reversed_interpretation="Excessive isolation verging on anti-social alienation, or resisting necessary introspective reflection out of fear of what lies inside.",
    ),
    TarotCard(
        id="wheel_of_fortune",
        name="Wheel of Fortune",
        name_zh="命运之轮",
        arcana=ArcanaType.MAJOR,
        number=10,
        element=Element.FIRE,
        astrology="Jupiter",
        archetype="Cycles of Destiny / Karma",
        keywords=CardMeaning(
            upright=["Good Luck", "Karma", "Life Cycles", "Destiny", "Turning Point", "Change"],
            reversed=["Bad Luck", "Resistance to Change", "Breaking Cycles", "Setbacks", "Unforeseen Delays"],
        ),
        description="A great wheel inscribed with Hebrew letters and alchemical symbols turns in the clouds, flanked by the Sphinx, Hermanubis, Typhon, and the four winged living creatures of Ezekiel.",
        upright_interpretation="Life's constant cycles shift in your favor. Adapt gracefully to change and welcome synchronous turning points.",
        reversed_interpretation="A string of bad luck or clinging rigidly to what was. Remember that the wheel never stops turning; this phase too shall pass.",
    ),
    TarotCard(
        id="justice",
        name="Justice",
        name_zh="正义",
        arcana=ArcanaType.MAJOR,
        number=11,
        element=Element.AIR,
        astrology="Libra",
        archetype="Truth & Equity / Law",
        keywords=CardMeaning(
            upright=["Justice", "Fairness", "Truth", "Cause and Effect", "Law", "Accountability"],
            reversed=["Unfairness", "Lack of Accountability", "Dishonesty", "Bias", "Legal Injustice"],
        ),
        description="A regal figure sits between stone pillars holding an upright double-edged sword in the right hand and balanced scales in the left hand.",
        upright_interpretation="Act with utmost fairness and objectivity. You reap what you sow, and karmic equilibrium will be restored.",
        reversed_interpretation="Dishonesty, unfair treatment, or evading personal responsibility. Rectify biases and face truth squarely.",
    ),
    TarotCard(
        id="the_hanged_man",
        name="The Hanged Man",
        name_zh="倒吊人",
        arcana=ArcanaType.MAJOR,
        number=12,
        element=Element.WATER,
        astrology="Neptune",
        archetype="Sacrifice & Surrender / New Perspective",
        keywords=CardMeaning(
            upright=["Surrender", "New Perspective", "Letting Go", "Pause", "Sacrifice", "Enlightenment"],
            reversed=["Stalling", "Resistance", "Needless Sacrifice", "Martyrdom", "Delay"],
        ),
        description="A serene youth hangs upside down by one ankle from a living wooden T-cross, with arms behind his back forming an inverted triangle and a golden halo glowing around his head.",
        upright_interpretation="Voluntarily pause and surrender your need for control to perceive the world from an inverted, enlightened perspective.",
        reversed_interpretation="Senseless martyrdom, procrastination, or stubborn resistance to inevitable surrender and change.",
    ),
    TarotCard(
        id="death",
        name="Death",
        name_zh="死神",
        arcana=ArcanaType.MAJOR,
        number=13,
        element=Element.WATER,
        astrology="Scorpio",
        archetype="Transformation / The Rebirth",
        keywords=CardMeaning(
            upright=["Endings", "Change", "Transformation", "Transition", "Rebirth", "Letting Go"],
            reversed=["Resistance to Change", "Fear of Transformation", "Stagnation", "Decay", "Holding On"],
        ),
        description="A black-armored skeleton riding a white horse carries a black banner emblazoned with a white mystic rose, while king, child, and maiden fall before him as the sun rises between two towers.",
        upright_interpretation="A definitive chapter closes so a profound new cycle can begin. Release the obsolete to welcome vital transformation.",
        reversed_interpretation="Clinging desperately to expired situations or toxic dynamics out of dread of the unknown. Allow the old to clear away.",
    ),
    TarotCard(
        id="temperance",
        name="Temperance",
        name_zh="节制",
        arcana=ArcanaType.MAJOR,
        number=14,
        element=Element.FIRE,
        astrology="Sagittarius",
        archetype="The Alchemist / Balance & Synthesis",
        keywords=CardMeaning(
            upright=["Balance", "Moderation", "Patience", "Purpose", "Harmony", "Integration"],
            reversed=["Imbalance", "Excess", "Extremes", "Lack of Patience", "Discord"],
        ),
        description="A winged angel with one foot in water and one on land pours liquid back and forth between two golden chalices without spilling a drop.",
        upright_interpretation="Blend opposing elements with patience, moderation, and harmonious alchemy to discover inner equilibrium and purpose.",
        reversed_interpretation="Excessive indulgence, impatience, or discordant conflict between polarized areas of life. Rebalance your energies.",
    ),
    TarotCard(
        id="the_devil",
        name="The Devil",
        name_zh="恶魔",
        arcana=ArcanaType.MAJOR,
        number=15,
        element=Element.EARTH,
        astrology="Capricorn",
        archetype="The Shadow / Bondage & Illusion",
        keywords=CardMeaning(
            upright=["Shadow Self", "Attachment", "Addiction", "Restriction", "Materialism", "Obsession"],
            reversed=["Release", "Breaking Free", "Overcoming Addiction", "Freedom", "Restoring Control"],
        ),
        description="A horned Baphomet satyr perches atop an altar to which a naked man and woman are loosely chained by their necks, holding a downward-pointing torch.",
        upright_interpretation="Unmask unconscious chains of materialism, unhealthy dependency, or compulsive behavioral traps; recognize that the chains are loose.",
        reversed_interpretation="Breaking free from toxic addictions, destructive habits, or codependent entanglements. Reclaiming personal sovereignty.",
    ),
    TarotCard(
        id="the_tower",
        name="The Tower",
        name_zh="高塔",
        arcana=ArcanaType.MAJOR,
        number=16,
        element=Element.FIRE,
        astrology="Mars",
        archetype="The Cataclysm / Sudden Awakening",
        keywords=CardMeaning(
            upright=["Sudden Upheaval", "Disaster", "Revelation", "Awakening", "Breakdown", "Chaos"],
            reversed=["Averting Disaster", "Delaying Inevitable", "Fear of Suffering", "Internal Upheaval"],
        ),
        description="Lightning strikes the golden crown of a stone fortress tower perched on a jagged mountain, setting it ablaze while two figures plummet into the abyss.",
        upright_interpretation="Sudden, shattering collapse of false structures and illusions. Though painful, it clears ground for authentic rebuilding.",
        reversed_interpretation="Postponing an inevitable collapse, or experiencing a silent internal crisis of belief. Embrace the necessary tear-down.",
    ),
    TarotCard(
        id="the_star",
        name="The Star",
        name_zh="星星",
        arcana=ArcanaType.MAJOR,
        number=17,
        element=Element.AIR,
        astrology="Aquarius",
        archetype="Hope / The Cosmic Guiding Light",
        keywords=CardMeaning(
            upright=["Hope", "Faith", "Purpose", "Renewal", "Spirituality", "Inspiration"],
            reversed=["Lack of Faith", "Despair", "Discouragement", "Pessimism", "Disconnection"],
        ),
        description="A naked maiden kneels beside a pool pouring living water onto land and water from two urns under a night sky lit by a large radiant yellow star and seven smaller stars.",
        upright_interpretation="A beacon of tranquil hope, deep spiritual rejuvenation, and serene inspiration following times of darkness and turmoil.",
        reversed_interpretation="Temporary loss of hope, cynicism, or despair. Rekindle your trust in the universe and reconnect with your inner light.",
    ),
    TarotCard(
        id="the_moon",
        name="The Moon",
        name_zh="月亮",
        arcana=ArcanaType.MAJOR,
        number=18,
        element=Element.WATER,
        astrology="Pisces",
        archetype="The Illusion / The Shadow Landscape",
        keywords=CardMeaning(
            upright=["Illusion", "Fear", "Anxiety", "Subconscious", "Intuition", "Uncertainty"],
            reversed=["Release of Fear", "Unveiling Secrets", "Clarity", "Overcoming Anxiety", "Truth"],
        ),
        description="A full moon with a serene face gazes down as a crayfish crawls from the deep water onto a winding path guarded by a howling dog and wolf between two towers.",
        upright_interpretation="Navigate through murky illusions, shadowy anxieties, and psychological uncertainties by trusting instinct through the dark.",
        reversed_interpretation="Shadows recede to reveal lucid clarity and hidden truths, dispelling irrational phobias and deceptive facades.",
    ),
    TarotCard(
        id="the_sun",
        name="The Sun",
        name_zh="太阳",
        arcana=ArcanaType.MAJOR,
        number=19,
        element=Element.FIRE,
        astrology="Sun",
        archetype="The Radiant Self / Vitality & Truth",
        keywords=CardMeaning(
            upright=["Joy", "Success", "Celebration", "Positivity", "Vitality", "Warmth"],
            reversed=["Temporary Sadness", "Overly Optimistic", "Clouded Joy", "Egoism", "Blocked Energy"],
        ),
        description="A naked child crowned with flowers and a red feather rides joyfully upon a gentle white horse before a stone wall topped with blooming sunflowers under a blazing sun.",
        upright_interpretation="Unabashed joy, radiant warmth, creative triumph, and lucid vitality illuminate all aspects of your endeavors.",
        reversed_interpretation="Temporary clouds obscuring enthusiasm or unrealistic optimism that ignores practical realities. Joy remains just behind the clouds.",
    ),
    TarotCard(
        id="judgement",
        name="Judgement",
        name_zh="审判",
        arcana=ArcanaType.MAJOR,
        number=20,
        element=Element.FIRE,
        astrology="Pluto",
        archetype="The Awakening / The Higher Calling",
        keywords=CardMeaning(
            upright=["Judgement", "Rebirth", "Inner Calling", "Absolution", "Awakening", "Forgiveness"],
            reversed=["Self-doubt", "Harsh Self-judgement", "Ignoring Calling", "Guilt", "Stagnation"],
        ),
        description="Archangel Gabriel blows a golden trumpet adorned with a banner of St. George, as men, women, and children rise with outstretched arms from their tombs against icy peaks.",
        upright_interpretation="Answer the clarion call of your higher self, evaluate your past deeds with forgiveness, and step into glorious spiritual rebirth.",
        reversed_interpretation="Paralyzing self-blame, harboring guilt, or ignoring the urgent inner call to step up and transform your life.",
    ),
    TarotCard(
        id="the_world",
        name="The World",
        name_zh="世界",
        arcana=ArcanaType.MAJOR,
        number=21,
        element=Element.EARTH,
        astrology="Saturn",
        archetype="Wholeness / Cosmic Completion",
        keywords=CardMeaning(
            upright=["Completion", "Integration", "Accomplishment", "Travel", "Fulfillment", "Wholeness"],
            reversed=["Incompletion", "Lack of Closure", "Shortcuts", "Delays", "Emptiness"],
        ),
        description="A dancing figure wrapped in purple cloth holds two wands inside a lush green laurel wreath, framed by the four cherubic figures of the evangelists in the four corners.",
        upright_interpretation="The grand culmination of a long journey, deep cosmic integration, fulfillment, and harmonious unity with the cosmos.",
        reversed_interpretation="Nearing the finish line but hindered by incomplete loose ends or seeking hasty shortcuts. Seek true closure before moving on.",
    ),
]
