"""Tarot card definitions for the 78-card Rider-Waite-Smith deck."""

from __future__ import annotations

from tarot.knowledge.models import Arcana, Element, Planet, Suit, TarotCard, Zodiac

MAJOR_ARCANA: list[TarotCard] = [
    TarotCard(
        id="the-fool",
        name="The Fool",
        number=0,
        arcana=Arcana.MAJOR,
        element=Element.AIR,
        planet=Planet.URANUS,
        keywords=["beginnings", "innocence", "spontaneity", "free spirit"],
        upright_meaning=(
            "A leap of faith into the unknown; new beginnings and unlimited potential."
        ),
        reversed_meaning="Recklessness, naivety, or fear of stepping into the unknown.",
        description=(
            "A young traveler stands at the edge of a cliff, gazing skyward, "
            "a small dog at his heels."
        ),
        advice="Embrace the journey with an open heart, but remain aware of your surroundings.",
    ),
    TarotCard(
        id="the-magician",
        name="The Magician",
        number=1,
        arcana=Arcana.MAJOR,
        element=Element.AIR,
        planet=Planet.MERCURY,
        keywords=["manifestation", "resourcefulness", "power", "inspired action"],
        upright_meaning=(
            "You have all the tools you need to manifest your desires; take focused action."
        ),
        reversed_meaning="Manipulation, untapped talents, or misdirected energy.",
        description=(
            "A figure stands before a table bearing the tools of the four suits, "
            "one arm raised to the sky."
        ),
        advice="Align intention with action; use your skills deliberately.",
    ),
    TarotCard(
        id="the-high-priestess",
        name="The High Priestess",
        number=2,
        arcana=Arcana.MAJOR,
        element=Element.WATER,
        planet=Planet.MOON,
        keywords=["intuition", "sacred knowledge", "divine feminine", "subconscious"],
        upright_meaning="Trust your inner voice; hidden knowledge and intuition are your guides.",
        reversed_meaning="Secrets, disconnection from intuition, or repressed emotions.",
        description=(
            "A serene woman sits between black and white pillars, a scroll in her lap "
            "and a crescent moon at her feet."
        ),
        advice="Listen more than you speak; let intuition surface before acting.",
    ),
    TarotCard(
        id="the-empress",
        name="The Empress",
        number=3,
        arcana=Arcana.MAJOR,
        element=Element.EARTH,
        planet=Planet.VENUS,
        keywords=["femininity", "beauty", "nature", "nurturing", "abundance"],
        upright_meaning="Creativity, fertility, and the flourishing of ideas or relationships.",
        reversed_meaning="Creative block, dependence, or neglect of self-care.",
        description=(
            "A crowned woman sits in a lush field of wheat, surrounded by trees "
            "and a flowing river."
        ),
        advice="Nurture yourself and your projects; abundance grows from care.",
    ),
    TarotCard(
        id="the-emperor",
        name="The Emperor",
        number=4,
        arcana=Arcana.MAJOR,
        element=Element.FIRE,
        zodiac=Zodiac.ARIES,
        keywords=["authority", "structure", "control", "fatherhood"],
        upright_meaning="Establish order, set boundaries, and lead with discipline and reason.",
        reversed_meaning="Tyranny, rigidity, or lack of self-discipline.",
        description=(
            "A stern ruler sits on a stone throne adorned with rams' heads, "
            "holding an orb and scepter."
        ),
        advice="Create structure; take responsibility and lead with fairness.",
    ),
    TarotCard(
        id="the-hierophant",
        name="The Hierophant",
        number=5,
        arcana=Arcana.MAJOR,
        element=Element.EARTH,
        zodiac=Zodiac.TAURUS,
        keywords=["tradition", "spiritual wisdom", "religious beliefs", "conformity"],
        upright_meaning="Seek guidance from established wisdom, mentors, or spiritual teachings.",
        reversed_meaning="Rebellion, unconventional paths, or challenging outdated beliefs.",
        description=(
            "A religious figure blesses two acolytes from a raised throne, "
            "keys crossed at his feet."
        ),
        advice="Honor tradition while discerning which rules truly serve you.",
    ),
    TarotCard(
        id="the-lovers",
        name="The Lovers",
        number=6,
        arcana=Arcana.MAJOR,
        element=Element.AIR,
        zodiac=Zodiac.GEMINI,
        keywords=["love", "harmony", "relationships", "choices", "values"],
        upright_meaning="A meaningful union or choice aligned with your deepest values.",
        reversed_meaning="Imbalance, misalignment, or difficult relational choices.",
        description=(
            "A couple stands beneath an angel while a tree of knowledge and "
            "a tree of life rise behind them."
        ),
        advice="Choose with integrity; let love and values guide the decision.",
    ),
    TarotCard(
        id="the-chariot",
        name="The Chariot",
        number=7,
        arcana=Arcana.MAJOR,
        element=Element.WATER,
        zodiac=Zodiac.CANCER,
        keywords=["control", "willpower", "success", "action", "determination"],
        upright_meaning=(
            "Victory through focus and discipline; channel opposing forces toward a single goal."
        ),
        reversed_meaning=(
            "Aggression, lack of direction, or being pulled in conflicting directions."
        ),
        description=(
            "A warrior stands in a chariot drawn by two sphinxes of opposite colors, "
            "holding no reins."
        ),
        advice="Harness your willpower; stay the course despite distractions.",
    ),
    TarotCard(
        id="strength",
        name="Strength",
        number=8,
        arcana=Arcana.MAJOR,
        element=Element.FIRE,
        zodiac=Zodiac.LEO,
        keywords=["strength", "courage", "persuasion", "influence", "compassion"],
        upright_meaning="Inner fortitude and gentle persistence tame even the wildest challenges.",
        reversed_meaning="Self-doubt, repressed emotions, or brute force over patience.",
        description=(
            "A woman calmly closes the jaws of a lion, wearing a garland of flowers "
            "and an infinity symbol."
        ),
        advice="Lead with compassion; true strength is patient and steady.",
    ),
    TarotCard(
        id="the-hermit",
        name="The Hermit",
        number=9,
        arcana=Arcana.MAJOR,
        element=Element.EARTH,
        zodiac=Zodiac.VIRGO,
        keywords=["soul-searching", "introspection", "being alone", "inner guidance"],
        upright_meaning="Withdraw to seek inner truth; wisdom comes from solitary reflection.",
        reversed_meaning="Isolation, loneliness, or avoidance of necessary introspection.",
        description=(
            "A robed figure stands on a snowy peak, holding a lantern that emits "
            "a six-pointed star."
        ),
        advice="Make space for quiet reflection; the answers are within.",
    ),
    TarotCard(
        id="wheel-of-fortune",
        name="Wheel of Fortune",
        number=10,
        arcana=Arcana.MAJOR,
        element=Element.FIRE,
        planet=Planet.JUPITER,
        keywords=["good luck", "karma", "life cycles", "destiny", "turning point"],
        upright_meaning="A turning point; cycles shift and fortune favors the prepared.",
        reversed_meaning="Bad luck, resistance to change, or feeling trapped by fate.",
        description="A great wheel turns, surrounded by sphinx, serpent, and Anubis figures.",
        advice="Flow with change; what rises will fall and rise again.",
    ),
    TarotCard(
        id="justice",
        name="Justice",
        number=11,
        arcana=Arcana.MAJOR,
        element=Element.AIR,
        zodiac=Zodiac.LIBRA,
        keywords=["justice", "fairness", "truth", "cause and effect", "law"],
        upright_meaning="Fairness, accountability, and the impartial weighing of choices.",
        reversed_meaning="Injustice, dishonesty, or avoidance of consequences.",
        description="A robed figure holds balanced scales in one hand and a sword in the other.",
        advice="Act with integrity; consider all sides before deciding.",
    ),
    TarotCard(
        id="the-hanged-man",
        name="The Hanged Man",
        number=12,
        arcana=Arcana.MAJOR,
        element=Element.WATER,
        planet=Planet.NEPTUNE,
        keywords=["pause", "surrender", "letting go", "new perspective"],
        upright_meaning="Suspend action and look at the situation from a new angle.",
        reversed_meaning="Stalling, resistance, or sacrificing for no gain.",
        description="A man hangs upside down by one foot from a tree, serene and haloed.",
        advice="Let go of control; surrender can reveal what force cannot.",
    ),
    TarotCard(
        id="death",
        name="Death",
        number=13,
        arcana=Arcana.MAJOR,
        element=Element.WATER,
        zodiac=Zodiac.SCORPIO,
        keywords=["endings", "change", "transformation", "transition"],
        upright_meaning="A necessary ending clears the way for transformation and renewal.",
        reversed_meaning="Resistance to change, stagnation, or painful prolongation.",
        description=(
            "A skeletal figure in armor rides a white horse, a flag bearing a rose in hand."
        ),
        advice="Release what no longer serves; transformation follows endings.",
    ),
    TarotCard(
        id="temperance",
        name="Temperance",
        number=14,
        arcana=Arcana.MAJOR,
        element=Element.FIRE,
        zodiac=Zodiac.SAGITTARIUS,
        keywords=["balance", "moderation", "patience", "purpose", "meaning"],
        upright_meaning="Blend opposing forces with patience; seek harmony and moderation.",
        reversed_meaning="Imbalance, excess, or lack of long-term vision.",
        description=("An angel pours water between two cups, one foot on land and one in a pool."),
        advice="Find the middle path; moderation creates sustainable progress.",
    ),
    TarotCard(
        id="the-devil",
        name="The Devil",
        number=15,
        arcana=Arcana.MAJOR,
        element=Element.EARTH,
        zodiac=Zodiac.CAPRICORN,
        keywords=["shadow self", "attachment", "addiction", "restriction", "sexuality"],
        upright_meaning="Recognize the chains of attachment and illusion that bind you.",
        reversed_meaning="Breaking free, releasing limiting beliefs, or reclaiming power.",
        description=(
            "A horned figure presides over two chained figures, their bonds loose enough to remove."
        ),
        advice="Examine what holds you captive; freedom begins with awareness.",
    ),
    TarotCard(
        id="the-tower",
        name="The Tower",
        number=16,
        arcana=Arcana.MAJOR,
        element=Element.FIRE,
        planet=Planet.MARS,
        keywords=["sudden change", "upheaval", "chaos", "revelation", "awakening"],
        upright_meaning="A sudden shake-up dismantles false structures; truth is revealed.",
        reversed_meaning="Avoiding disaster, delayed upheaval, or resisting necessary change.",
        description=(
            "Lightning strikes a tower, sending figures and flames tumbling from its heights."
        ),
        advice="Let falling structures crumble; rebuild on a foundation of truth.",
    ),
    TarotCard(
        id="the-star",
        name="The Star",
        number=17,
        arcana=Arcana.MAJOR,
        element=Element.AIR,
        zodiac=Zodiac.AQUARIUS,
        keywords=["hope", "faith", "purpose", "renewal", "spirituality"],
        upright_meaning="Hope, inspiration, and serene renewal after difficulty.",
        reversed_meaning="Despair, disconnection, or loss of faith.",
        description="A nude figure kneels by water, pouring jugs beneath a starry sky.",
        advice="Trust in renewal; keep hope alive through gentle, steady action.",
    ),
    TarotCard(
        id="the-moon",
        name="The Moon",
        number=18,
        arcana=Arcana.MAJOR,
        element=Element.WATER,
        zodiac=Zodiac.PISCES,
        keywords=["illusion", "fear", "anxiety", "subconscious", "intuition"],
        upright_meaning="Navigate uncertainty and illusion by trusting intuition over appearances.",
        reversed_meaning="Confusion, fear, or repressed emotions surfacing.",
        description=(
            "A full moon shines over a winding path flanked by a dog and a wolf, "
            "with a crayfish emerging from water."
        ),
        advice="Move through uncertainty slowly; trust your instincts in the dark.",
    ),
    TarotCard(
        id="the-sun",
        name="The Sun",
        number=19,
        arcana=Arcana.MAJOR,
        element=Element.FIRE,
        planet=Planet.SUN,
        keywords=["positivity", "fun", "warmth", "success", "vitality"],
        upright_meaning="Joy, clarity, and radiant success; everything is illuminated.",
        reversed_meaning="Temporary sadness, pessimism, or blocked joy.",
        description=(
            "A smiling child rides a white horse beneath a blazing sun, a banner in hand."
        ),
        advice="Celebrate life; share your light generously with others.",
    ),
    TarotCard(
        id="judgement",
        name="Judgement",
        number=20,
        arcana=Arcana.MAJOR,
        element=Element.FIRE,
        planet=Planet.PLUTO,
        keywords=["judgement", "rebirth", "inner calling", "absolution"],
        upright_meaning="A call to rise; heed your higher calling and embrace renewal.",
        reversed_meaning="Self-doubt, avoidance, or failure to learn from the past.",
        description=("An angel trumpets from the heavens while figures rise from coffins below."),
        advice="Answer the call to evolve; forgive yourself and move forward.",
    ),
    TarotCard(
        id="the-world",
        name="The World",
        number=21,
        arcana=Arcana.MAJOR,
        element=Element.EARTH,
        planet=Planet.SATURN,
        keywords=["completion", "integration", "accomplishment", "travel"],
        upright_meaning="A cycle completes; wholeness, achievement, and integration.",
        reversed_meaning="Incompletion, shortcuts, or lack of closure.",
        description=(
            "A dancer holds two wands within a laurel wreath, surrounded by four living creatures."
        ),
        advice="Honor your achievements; prepare for the next cycle with gratitude.",
    ),
]


# Minor Arcana court card rank mapping.
_COURT_RANKS = {
    "page": 11,
    "knight": 12,
    "queen": 13,
    "king": 14,
}


def _minor(
    rank: str | int,
    suit: Suit,
    element: Element,
    keywords: list[str],
    upright: str,
    reversed: str,
    description: str,
    advice: str,
) -> TarotCard:
    """Helper to build a Minor Arcana card."""
    if isinstance(rank, int):
        name = f"{rank} of {suit.value.capitalize()}"
        card_id = f"{rank}-of-{suit.value}"
        number = rank
    else:
        name = f"{rank.capitalize()} of {suit.value.capitalize()}"
        card_id = f"{rank}-of-{suit.value}"
        number = _COURT_RANKS[rank]
    return TarotCard(
        id=card_id,
        name=name,
        number=number,
        arcana=Arcana.MINOR,
        suit=suit,
        element=element,
        keywords=keywords,
        upright_meaning=upright,
        reversed_meaning=reversed,
        description=description,
        advice=advice,
    )


MINOR_ARCANA: list[TarotCard] = [
    # Wands
    _minor(
        1,
        Suit.WANDS,
        Element.FIRE,
        ["creation", "willpower", "inspiration", "desire"],
        "A spark of creative potential; the seed of a new venture.",
        "Lack of energy, delays, or unclear goals.",
        "A hand emerges from a cloud offering a sprouting wand.",
        "Seize the spark; channel inspiration into action.",
    ),
    _minor(
        2,
        Suit.WANDS,
        Element.FIRE,
        ["planning", "decisions", "discovery", "future"],
        "Planning for the future; choosing a direction with confidence.",
        "Fear of the unknown, poor planning, or playing it safe.",
        "A figure stands on a castle wall holding a globe and a wand.",
        "Map out your path; bold plans need a clear vision.",
    ),
    _minor(
        3,
        Suit.WANDS,
        Element.FIRE,
        ["expansion", "foresight", "leadership", "exploration"],
        "Progress and expansion; your ships are coming in.",
        "Obstacles, delays, or overconfidence in plans.",
        "A figure watches three ships sail away from a cliff.",
        "Look ahead; prepare to receive the fruits of your efforts.",
    ),
    _minor(
        4,
        Suit.WANDS,
        Element.FIRE,
        ["celebration", "harmony", "marriage", "community"],
        "Joyful celebration and stable community; a time to gather.",
        "Lack of support, instability, or celebration cut short.",
        "Four wands support a garland as figures celebrate beneath.",
        "Celebrate milestones; nurture your community.",
    ),
    _minor(
        5,
        Suit.WANDS,
        Element.FIRE,
        ["conflict", "competition", "tension", "diversity"],
        "Healthy competition or conflict; test your mettle.",
        "Avoiding conflict, inner turmoil, or petty disputes.",
        "Five figures clash wands in a spirited but non-lethal contest.",
        "Engage constructively; competition can sharpen you.",
    ),
    _minor(
        6,
        Suit.WANDS,
        Element.FIRE,
        ["victory", "recognition", "pride", "progress"],
        "Public recognition and triumph; ride the wave of success.",
        "Self-doubt, delayed recognition, or excessive pride.",
        "A rider on horseback is greeted with laurels by a cheering crowd.",
        "Accept praise gracefully; let success fuel further growth.",
    ),
    _minor(
        7,
        Suit.WANDS,
        Element.FIRE,
        ["perseverance", "defense", "maintaining control"],
        "Stand your ground against challenges; defend your position.",
        "Overwhelm, giving up, or inability to set boundaries.",
        "A figure atop a hill fends off six wands raised below.",
        "Hold your ground; your resolve will see you through.",
    ),
    _minor(
        8,
        Suit.WANDS,
        Element.FIRE,
        ["speed", "action", "air travel", "movement"],
        "Rapid progress and swift communication; things move quickly.",
        "Delays, frustration, or hasty action causing errors.",
        "Eight wands fly through the air toward a distant target.",
        "Act decisively; momentum is on your side.",
    ),
    _minor(
        9,
        Suit.WANDS,
        Element.FIRE,
        ["resilience", "courage", "persistence", "test of faith"],
        "Last reserves of strength; persist despite weariness.",
        "Exhaustion, defensiveness, or feeling overwhelmed.",
        "A weary figure leans on a wand while eight more stand behind.",
        "Gather your strength; you are closer to the finish than you think.",
    ),
    _minor(
        10,
        Suit.WANDS,
        Element.FIRE,
        ["burden", "responsibility", "hard work", "stress"],
        "Heavy burdens and responsibilities; the weight of ambition.",
        "Release burdens, delegation failure, or burnout.",
        "A figure carries ten wands toward a distant village.",
        "Lighten your load; not every burden is yours to carry.",
    ),
    _minor(
        "page",
        Suit.WANDS,
        Element.FIRE,
        ["exploration", "excitement", "freedom", "discovery"],
        "A messenger of inspiration; eager exploration of new ideas.",
        "Lack of direction, scattered energy, or bad news.",
        "A young figure holds a wand and gazes at the sprouting tip.",
        "Follow your curiosity; let enthusiasm lead the way.",
    ),
    _minor(
        "knight",
        Suit.WANDS,
        Element.FIRE,
        ["action", "adventure", "fearlessness", "impulsiveness"],
        "Bold, passionate action; charge forward with courage.",
        "Recklessness, anger, or impulsive mistakes.",
        "A knight in armor rides a rearing horse, wand held high.",
        "Act with passion, but keep an eye on the consequences.",
    ),
    _minor(
        "queen",
        Suit.WANDS,
        Element.FIRE,
        ["confidence", "passion", "determination", "charisma"],
        "Warm, magnetic leadership; confident self-expression.",
        "Selfishness, jealousy, or demanding behavior.",
        "A crowned queen sits on a throne decorated with lions and sunflowers.",
        "Lead with warmth and authenticity; your fire inspires others.",
    ),
    _minor(
        "king",
        Suit.WANDS,
        Element.FIRE,
        ["leadership", "vision", "entrepreneurship", "honor"],
        "A visionary leader; bold, honorable, and inspiring.",
        "Impulsiveness, tyranny, or unrealistic expectations.",
        "A king holds a blossoming wand, a salamander at his feet.",
        "Lead with vision; inspire others through your example.",
    ),
    # Cups
    _minor(
        1,
        Suit.CUPS,
        Element.WATER,
        ["love", "new feelings", "emotional awakening", "intuition"],
        "The source of love and emotion; a new feeling overflows.",
        "Emotional block, repressed feelings, or emptiness.",
        "A cup overflows from a cloud, streams nourishing a lotus pond.",
        "Open your heart; let love and intuition flow.",
    ),
    _minor(
        2,
        Suit.CUPS,
        Element.WATER,
        ["unity", "partnership", "mutual attraction", "harmony"],
        "A balanced partnership; mutual respect and emotional union.",
        "Imbalance, broken bonds, or misaligned values.",
        "Two figures exchange cups beneath a winged lion and caduceus.",
        "Value reciprocity; true partnership is built on equality.",
    ),
    _minor(
        3,
        Suit.CUPS,
        Element.WATER,
        ["friendship", "community", "happiness", "celebration"],
        "Joyful connection and communal celebration; raise a glass.",
        "Overindulgence, gossip, or isolation from friends.",
        "Three women raise cups in a garden of ripe fruit.",
        "Celebrate with your circle; joy multiplies when shared.",
    ),
    _minor(
        4,
        Suit.CUPS,
        Element.WATER,
        ["apathy", "contemplation", "disconnectedness", "meditation"],
        "Emotional stagnation; reevaluate what truly fulfills you.",
        "Boredom, missed opportunities, or emotional withdrawal.",
        "A figure sits beneath a tree, three cups before them and one offered from a cloud.",
        "Look beyond the familiar; new emotional gifts are available.",
    ),
    _minor(
        5,
        Suit.CUPS,
        Element.WATER,
        ["loss", "grief", "disappointment", "mourning"],
        "Grief over loss; three cups spill while two remain standing.",
        "Acceptance, moving on, or finding hope after sorrow.",
        "A cloaked figure mourns three fallen cups, two upright behind.",
        "Honor your grief, but remember what still remains.",
    ),
    _minor(
        6,
        Suit.CUPS,
        Element.WATER,
        ["nostalgia", "childhood", "innocence", "joy"],
        "Fond memories and innocent joy; reconnect with the past.",
        "Living in the past, naivety, or unresolved childhood issues.",
        "Two children offer cups in a garden filled with flowers.",
        "Cherish happy memories; let them inform, not confine, you.",
    ),
    _minor(
        7,
        Suit.CUPS,
        Element.WATER,
        ["choices", "fantasy", "wishful thinking", "illusion"],
        "Many options, but beware of illusion; clarify your desires.",
        "Confusion, temptation, or lack of direction.",
        "A figure contemplates seven cups filled with visions and treasures.",
        "Discern fantasy from reality; choose with clear intent.",
    ),
    _minor(
        8,
        Suit.CUPS,
        Element.WATER,
        ["disappointment", "abandonment", "withdrawal", "escapism"],
        "Walking away from what no longer fulfills you.",
        "Fear of change, avoidance, or clinging to the past.",
        "A figure leaves eight cups behind to climb a moonlit mountain.",
        "Leave behind what is empty; seek deeper meaning.",
    ),
    _minor(
        9,
        Suit.CUPS,
        Element.WATER,
        ["contentment", "satisfaction", "gratitude", "wish come true"],
        "Emotional fulfillment and satisfaction; the wish card.",
        "Dissatisfaction, smugness, or taking blessings for granted.",
        "A figure sits before nine cups arranged in an arc.",
        "Savor your blessings; gratitude deepens contentment.",
    ),
    _minor(
        10,
        Suit.CUPS,
        Element.WATER,
        ["happiness", "home", "fulfillment", "emotional harmony"],
        "Lasting emotional happiness and harmonious family life.",
        "Broken harmony, family strife, or unrealistic ideals.",
        "A couple embraces beneath a rainbow of ten cups.",
        "Nurture the bonds that create true happiness.",
    ),
    _minor(
        "page",
        Suit.CUPS,
        Element.WATER,
        ["messenger", "creative beginnings", "intuition", "curiosity"],
        "A creative or emotional message; intuitive beginnings.",
        "Emotional immaturity, bad news, or creative block.",
        "A young figure holds a cup, a fish rising from it in surprise.",
        "Listen to your intuition; creative messages are arriving.",
    ),
    _minor(
        "knight",
        Suit.CUPS,
        Element.WATER,
        ["romance", "charm", "imagination", "beauty"],
        "A romantic offer or creative pursuit; follow your heart.",
        "Unrealistic ideals, emotional volatility, or disappointment.",
        "A knight in armor holds a cup, a dove emerging from it.",
        "Pursue beauty and connection, but keep your feet on the ground.",
    ),
    _minor(
        "queen",
        Suit.CUPS,
        Element.WATER,
        ["compassion", "calm", "comfort", "emotional security"],
        "Deep emotional wisdom and nurturing compassion.",
        "Emotional insecurity, martyrdom, or dependence.",
        "A queen sits on a throne by the sea, holding an ornate cup.",
        "Offer compassion freely; tend to your own heart first.",
    ),
    _minor(
        "king",
        Suit.CUPS,
        Element.WATER,
        ["emotional balance", "compassion", "diplomacy", "control"],
        "Mastery of emotions; balanced compassion and diplomacy.",
        "Emotional manipulation, moodiness, or withdrawal.",
        "A king sits on a throne amid waves, holding a cup and scepter.",
        "Lead with empathy; emotional maturity creates trust.",
    ),
    # Swords
    _minor(
        1,
        Suit.SWORDS,
        Element.AIR,
        ["clarity", "breakthrough", "new idea", "concentration"],
        "A moment of mental clarity; a powerful new idea emerges.",
        "confusion, chaos, or a destructive idea.",
        "A hand raises a double-edged sword from a cloud.",
        "Use your mind as a tool; clarity cuts through confusion.",
    ),
    _minor(
        2,
        Suit.SWORDS,
        Element.AIR,
        ["difficult choices", "indecision", "stalemate", "blocked emotions"],
        "A difficult decision requires clear thought, not emotion.",
        "Indecision, avoidance, or information overload.",
        "A blindfolded figure holds two crossed swords against a moonlit sea.",
        "Remove the blindfold; gather facts and decide with clarity.",
    ),
    _minor(
        3,
        Suit.SWORDS,
        Element.AIR,
        ["heartbreak", "grief", "sorrow", "emotional pain"],
        "Emotional pain and sorrow; a necessary passage through grief.",
        "Recovery, forgiveness, or moving past heartbreak.",
        "Three swords pierce a heart beneath stormy skies.",
        "Allow yourself to grieve; healing follows acknowledgment.",
    ),
    _minor(
        4,
        Suit.SWORDS,
        Element.AIR,
        ["rest", "restoration", "contemplation", "recuperation"],
        "Rest and recover; step back to regain mental clarity.",
        "Restlessness, burnout, or avoidance of necessary action.",
        "A knight rests on three swords while a fourth hangs on a wall.",
        "Pause to restore your mind; clarity returns with rest.",
    ),
    _minor(
        5,
        Suit.SWORDS,
        Element.AIR,
        ["conflict", "defeat", "winning at all costs", "betrayal"],
        "Conflict or hollow victory; beware of unethical tactics.",
        "Reconciliation, making amends, or past resentment.",
        "A figure collects swords while others walk away in defeat.",
        "Choose integrity over victory; repair what is broken.",
    ),
    _minor(
        6,
        Suit.SWORDS,
        Element.AIR,
        ["transition", "change", "rite of passage", "release"],
        "Moving away from difficulty toward calmer waters.",
        "Resistance to change, unfinished business, or stagnation.",
        "A boatman ferries figures and swords across a river.",
        "Leave turmoil behind; smoother waters lie ahead.",
    ),
    _minor(
        7,
        Suit.SWORDS,
        Element.AIR,
        ["deception", "strategy", "sneakiness", "getting away with something"],
        "Strategy or deception; be cautious of hidden motives.",
        "Coming clean, rethinking approach, or conscience.",
        "A figure sneaks away with five swords while two remain behind.",
        "Act with integrity; deception often backfires.",
    ),
    _minor(
        8,
        Suit.SWORDS,
        Element.AIR,
        ["restriction", "imprisonment", "self-victimization", "negative thoughts"],
        "Self-imposed limitations; negative thoughts bind you.",
        "Liberation, new perspective, or release from fear.",
        "A figure stands bound and blindfolded among eight swords.",
        "Your bonds are loose; free yourself from limiting beliefs.",
    ),
    _minor(
        9,
        Suit.SWORDS,
        Element.AIR,
        ["anxiety", "worry", "fear", "nightmares"],
        "Anxiety and sleepless worry; fears may be exaggerated.",
        "Hope, reaching out, or overcoming anxiety.",
        "A person sits up in bed, head in hands, nine swords on the wall.",
        "Name your fears; many lose power in the light.",
    ),
    _minor(
        10,
        Suit.SWORDS,
        Element.AIR,
        ["painful endings", "deep wounds", "betrayal", "loss", "crisis"],
        "A painful ending or betrayal; rock bottom precedes renewal.",
        "Recovery, regeneration, or resisting an inevitable end.",
        "A figure lies face down with ten swords in their back.",
        "The worst is over; rebuild slowly and gently.",
    ),
    _minor(
        "page",
        Suit.SWORDS,
        Element.AIR,
        ["curiosity", "new ideas", "thirst for knowledge", "communication"],
        "A thirst for truth and new ideas; eager mental exploration.",
        "Deception, gossip, or hasty conclusions.",
        "A young figure holds a sword upright, alert and watchful.",
        "Ask questions; seek truth with an open mind.",
    ),
    _minor(
        "knight",
        Suit.SWORDS,
        Element.AIR,
        ["action", "impulsiveness", "defending beliefs", "haste"],
        "Swift, decisive action; charge ahead with intellect.",
        "Impulsiveness, aggression, or reckless words.",
        "A knight charges forward on horseback, sword raised high.",
        "Act quickly but think first; words and actions have edges.",
    ),
    _minor(
        "queen",
        Suit.SWORDS,
        Element.AIR,
        ["independence", "unbiased judgement", "clear boundaries", "direct communication"],
        "Clear, honest communication and impartial judgement.",
        "Coldness, cruelty, or overly harsh judgement.",
        "A queen sits on a throne, sword raised, hand extended.",
        "Speak truth with compassion; clarity need not be cruel.",
    ),
    _minor(
        "king",
        Suit.SWORDS,
        Element.AIR,
        ["mental clarity", "intellectual power", "authority", "truth"],
        "Mastery of intellect and truth; decisive authority.",
        "Tyranny, manipulation, or cold rationality.",
        "A king sits on a throne, sword upright, gaze steady.",
        "Use your intellect wisely; authority is earned through truth.",
    ),
    # Pentacles
    _minor(
        1,
        Suit.PENTACLES,
        Element.EARTH,
        ["manifestation", "new financial opportunity", "prosperity", "abundance"],
        "A seed of material opportunity; prosperity is within reach.",
        "Lost opportunity, greed, or lack of planning.",
        "A hand offers a pentacle from a cloud above a lush garden.",
        "Invest wisely; nurture the seed of abundance.",
    ),
    _minor(
        2,
        Suit.PENTACLES,
        Element.EARTH,
        ["balance", "adaptability", "time management", "prioritization"],
        "Juggling responsibilities; balance material demands.",
        "Overwhelm, disorganization, or financial instability.",
        "A figure dances while balancing two pentacles within a lemniscate.",
        "Prioritize; balance is a dance, not a fixed state.",
    ),
    _minor(
        3,
        Suit.PENTACLES,
        Element.EARTH,
        ["teamwork", "collaboration", "learning", "implementation"],
        "Skillful collaboration; learning and building together.",
        "Lack of teamwork, poor craftsmanship, or disharmony.",
        "Three artisans consult over plans in a cathedral.",
        "Value expertise; great work is built through cooperation.",
    ),
    _minor(
        4,
        Suit.PENTACLES,
        Element.EARTH,
        ["security", "conservation", "frugality", "control"],
        "Holding on to resources; financial stability and caution.",
        "Greed, materialism, or resistance to change.",
        "A figure clutches four pentacles, two underfoot, one at heart.",
        "Hold resources wisely, but don't let fear close your heart.",
    ),
    _minor(
        5,
        Suit.PENTACLES,
        Element.EARTH,
        ["financial loss", "poverty", "lack mindset", "isolation"],
        "Material hardship or exclusion; seek help and community.",
        "Recovery from loss, renewed hope, or finding support.",
        "Two figures walk in snow past a lit church window.",
        "Reach out; help is closer than it appears.",
    ),
    _minor(
        6,
        Suit.PENTACLES,
        Element.EARTH,
        ["generosity", "charity", "giving", "prosperity", "sharing wealth"],
        "Generosity and fair exchange; give and receive with grace.",
        "Strings attached, debt, or imbalance in giving.",
        "A merchant distributes pentacles to two kneeling figures.",
        "Share your abundance; generosity creates flow.",
    ),
    _minor(
        7,
        Suit.PENTACLES,
        Element.EARTH,
        ["long-term view", "sustainable results", "perseverance", "investment"],
        "Patience and sustained effort; tend to your long-term goals.",
        "Impatience, lack of growth, or wasted effort.",
        "A figure pauses from work to admire seven growing pentacles.",
        "Trust the process; growth takes time and care.",
    ),
    _minor(
        8,
        Suit.PENTACLES,
        Element.EARTH,
        ["apprenticeship", "repetitive tasks", "mastery", "skill development"],
        "Diligent practice and skill development; mastery through repetition.",
        "Self-criticism, perfectionism, or meaningless toil.",
        "A craftsman hammers eight pentacles at a workbench.",
        "Keep practicing; expertise is built one repetition at a time.",
    ),
    _minor(
        9,
        Suit.PENTACLES,
        Element.EARTH,
        ["abundance", "luxury", "self-sufficiency", "financial independence"],
        "Material comfort and self-sufficiency; enjoy the fruits of labor.",
        "Overindulgence, dependence, or superficiality.",
        "A figure stands in a lush garden, a falcon on their gloved hand.",
        "Enjoy your success; independence is worth celebrating.",
    ),
    _minor(
        10,
        Suit.PENTACLES,
        Element.EARTH,
        ["wealth", "financial security", "family", "long-term success"],
        "Lasting wealth and family legacy; generational abundance.",
        "Financial failure, family discord, or short-term thinking.",
        "An elder and child stand before an archway of ten pentacles.",
        "Build for the long term; legacy matters more than quick gains.",
    ),
    _minor(
        "page",
        Suit.PENTACLES,
        Element.EARTH,
        ["manifestation", "financial opportunity", "skill development", "ambition"],
        "A new opportunity to build skills or wealth; eager study.",
        "Lack of progress, greed, or short-sightedness.",
        "A young figure studies a pentacle held aloft in a garden.",
        "Commit to learning; practical skills open doors.",
    ),
    _minor(
        "knight",
        Suit.PENTACLES,
        Element.EARTH,
        ["hard work", "productivity", "routine", "conservatism"],
        "Steady, methodical progress; diligence brings results.",
        "Stagnation, boredom, or stubborn resistance to change.",
        "A knight holds a pentacle, horse standing still in a plowed field.",
        "Stay the course; slow and steady wins the race.",
    ),
    _minor(
        "queen",
        Suit.PENTACLES,
        Element.EARTH,
        ["nurturing", "practical", "abundance", "generosity", "comfort"],
        "Generous, practical nurturing; abundance shared freely.",
        "Overprotectiveness, financial dependence, or smothering.",
        "A queen sits in a garden, holding a pentacle, a rabbit nearby.",
        "Care for others practically; abundance grows when shared.",
    ),
    _minor(
        "king",
        Suit.PENTACLES,
        Element.EARTH,
        ["wealth", "business", "leadership", "security", "discipline"],
        "Mastery of material affairs; disciplined, prosperous leadership.",
        "Materialism, stubbornness, or greed.",
        "A king sits on a throne carved with bulls, holding a pentacle.",
        "Lead with discipline; lasting wealth serves a greater purpose.",
    ),
]


ALL_CARDS: list[TarotCard] = MAJOR_ARCANA + MINOR_ARCANA
